### ISSUE TITLE
AssertionError when opening a project

### ISSUE THREAD

**Issue by gastaldi** [asciidoctor/asciidoctor-intellij-plugin#110]
I get the following error when opening a project in Intellij containing only a pom.xml and a Main class
````
java.lang.AssertionError
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:212)
	at com.intellij.psi.impl.PsiManagerImpl.findViewProvider(PsiManagerImpl.java:191)
	at org.asciidoc.intellij.AsciiDocLanguage.isAsciiDocFile(AsciiDocLanguage.java:48)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditorProvider.accept(AsciiDocPreviewEditorProvider.java:44)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$2.compute(FileEditorProviderManagerImpl.java:94)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl$2.compute(FileEditorProviderManagerImpl.java:88)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
	at com.intellij.openapi.fileEditor.impl.FileEditorProviderManagerImpl.getProviders(FileEditorProviderManagerImpl.java:88)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:840)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:810)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$11.run(FileEditorManagerImpl.java:790)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:787)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:728)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:145)
	at org.jboss.forge.plugin.idea.util.IDEUtil.openFile(IDEUtil.java:99)
	at org.jboss.forge.plugin.idea.util.IDEUtil.openSingleSelection(IDEUtil.java:92)
	at org.jboss.forge.plugin.idea.util.IDEUtil.openSelection(IDEUtil.java:81)
	at org.jboss.forge.plugin.idea.ui.wizard.ForgeCommandTask.lambda$run$0(ForgeCommandTask.java:60)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
````

**Comment by ehmkah** [comment]
Could you send a link if you have your mini project in github? Maybe something strange, so I could see directly in your project.

**Comment by gastaldi** [comment]
I managed to reproduce by creating a project using the JBoss Forge plugin. Follow these steps to reproduce: 

1. Install the JBoss Forge Intellij Plugin (https://plugins.jetbrains.com/plugin/7515)
2. After restarting IDEA, press Ctrl + Alt + 4 (or Command + Option + 4 if on Mac) to open a command popup
3. Choose `Project : New` and type a project name (demo for instance) and press Finish
4. When the IDE opens the new project window, you should see the error.

**Comment by ehmkah** [comment]
Difficult. I can not reproduce your error :-( If copy the steps you provide everything looks good (the jboss plugin does not create a pom file?).

Anyway. Would you be so kind to open the following project https://github.com/ehmkah/asciidoctor_intellij_example/ and say whether it works for you or not? (it only has one pom and one main class as you wrote). If it works for you maybe you could just push your empty project to github so I can clone and see the error. Hope it will not be something difficult. Thanks for your help.

**Comment by gastaldi** [comment]
Hi Michael,
Thanks for looking at this. I cannot reproduce by importing the project,
only when creating the project using the JBoss Forge plugin. I can create a
screencast reproducing the error if you need.
Em 08/05/2016 08:56, "Michael Krauße" <notifications@github.com> escreveu:

Difficult. I can not reproduce your error :-( If copy the steps you provide
everything looks good (the jboss plugin does not create a pom file?).

Anyway. Would you be so kind to open the following project
https://github.com/ehmkah/asciidoctor_intellij_example/ and say whether it
works for you or not? (it only has one pom and one main class as you
wrote). If it works for you maybe you could just push your empty project to
github so I can clone and see the error. Hope it will not be something
difficult. Thanks for your help.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/110#issuecomment-217711652>

**Comment by ehmkah** [comment]
Than I would take the screencast, maybe it will help

**Comment by gastaldi** [comment]
Here is the screencast: https://www.youtube.com/watch?v=NyYDPtLm8bY
Let me know if you need anything else

**Comment by gastaldi** [comment]
Just created a PR for the issue. I suppose that should fix it

**Comment by ehmkah** [comment]
Very good! I would have written a unit test too but for your luck I am not the project owner so I can not force you.😉 Maybe you could make a line to readme file where changes are tracked.

**Comment by bodiam** [comment]
Well, I also won't force you ;-) You could try to write one if you want,
otherwise I don't mind merging it!

**Comment by krasa** [comment]
That won't fix it, and you don't even need to try that. 
AsciiDocLanguage#isAsciiDocFile is called from places which have @NotNull, so you can be sure that those parameters won't be null.

And if you look into IntelliJ sources, you will see what causes the problem:
```
  @Override
  @NotNull
  public FileViewProvider findViewProvider(@NotNull final VirtualFile file) {
    assert !file.isDirectory();
    ....
  }
```
So check for that, and instead of checking for null, replace those horribly useless `final` keywords by @NotNull to get nice code inspections.

**Comment by gastaldi** [comment]
Ah good catch! Will change the PR then. Thanks

**Comment by gastaldi** [comment]
PR https://github.com/asciidoctor/asciidoctor-intellij-plugin/pull/113 updated!
