### ISSUE TITLE
Exception in IntelliJ "Unbalanced tree. Most probably caused by unbalanced markers"

### ISSUE THREAD

**Issue by wlk** [asciidoctor/asciidoctor-intellij-plugin#119]
When opening this file: https://github.com/wlk/kamon-prometheus/blob/master/README.asciidoc I get following exception:

IntelliJ version: 
```
IntelliJ IDEA 2016.2.1 EAP
Build #IU-162.1447.7, built on July 20, 2016
JRE: 1.8.0_76-release-b216 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

Plugin version:
```
Version: 0.13
```

Exception:
```
Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem
```

```
Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem
language: Language: AsciiDoc, 
context: '--------------------------

Note that the above configuration uses the default `scrape_interval` (one
minute, matching _kamon-prometheus’_ default.) and `metrics_path` (`/metrics`).


Development
-----------

[[building]]
=== Building the library

You can use `sbt` to build the library, but you will need to have Google’s
protocol buffers compiler `protoc` on your path.  You can
https://developers.google.com/protocol-buffers/docs/downloads[download]
Protocol buffers directly from Google.  However, there may be simpler options.
For example, on OS X, you can use http://brew.sh[homebrew] and just `brew
install protobuf`.

Additionally, to build the demo, you will need to have Docker set up.


=== Contributing to the project

Outside contributions to this project are welcome!  Please review
link:CONTRIBUTING.md[] for more information.


Future plans
------------

Check out the https://github.com/MonsantoCo/kamon-prometheus/issues[issues]
page.  Please star issues that are important to you.
'
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.lang.impl.PsiBuilderImpl.a(PsiBuilderImpl.java:1307)
	at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:1262)
	at com.intellij.lang.impl.PsiBuilderImpl.e(PsiBuilderImpl.java:1140)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:1124)
	at org.asciidoc.intellij.parser.AsciiDocParser.parse(AsciiDocParser.java:23)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:85)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.a(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:835)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:515)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:501)
	at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:629)
	at com.intellij.psi.util.PsiUtilCore.getElementAtOffset(PsiUtilCore.java:420)
	at com.intellij.psi.util.PsiUtilBase.getLanguageInEditor(PsiUtilBase.java:73)
	at com.intellij.psi.util.PsiUtilBase.getPsiFileInEditor(PsiUtilBase.java:107)
	at com.intellij.psi.util.PsiUtilBase.getPsiFileInEditor(PsiUtilBase.java:96)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lookForInjectedAndMatchBracesInOtherThread(BraceHighlightingHandler.java:123)
	at com.intellij.codeInsight.highlighting.BraceHighlighter.updateBraces(BraceHighlighter.java:127)
	at com.intellij.codeInsight.highlighting.BraceHighlighter$4.focusGained(BraceHighlighter.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy35.focusGained(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorImpl.b(EditorImpl.java:1171)
	at com.intellij.openapi.editor.impl.EditorImpl.access$4200(EditorImpl.java:125)
	at com.intellij.openapi.editor.impl.EditorImpl$8.focusGained(EditorImpl.java:1017)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:219)
	at java.awt.Component.processFocusEvent(Component.java:6422)
	at java.awt.Component.processEvent(Component.java:6289)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:986)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:610)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mojavelinux** [comment]
I want to clarify that the two-line section titles are supported in AsciiDoc, their usage is simply discouraged. In Asciidoctor, we consider this syntax deprecated. We are not requiring/requesting tools to support it. The single-line section title is the "modern", recommended syntax.

**Comment by leonard84** [comment]
Maybe it doesn't have to be supported but the plugin should not fail so spectacular either. 

We also used the "old" syntax as it provides more visual weight for the more important sections. The "=" does the inverse in this regard.

**Comment by kastork** [comment]
I believe this problem presents with single-line section titles too...

Start with a list
```[asciidoc]
= Doc

etc

== Section

etc

=== Subsection

. one
. two
. three
```

Decide to put it in a new subsection.

```[asciidoc]
= Doc

etc

== Section

etc

=== Subsection

etc

==== Holy exception Batman
. one
. two
. three
```

```
11:10 AM	Throwable
				Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem
```

**Comment by ahus1** [comment]
The release 0.14.3 is now available and fixes this problem. 

I worked with the minimal example from @kastork, thank you very much!

I wasn't able to catch the exception, as the exception is created outside of the plugin. 

I had to fix the creator of the PSI tree. If you experience this exception with other texts, please provide a (minimal) example.
