### ISSUE TITLE
AbstractMethodError on closing a .adoc file

### ISSUE THREAD

**Issue by Matthias-Ni** [asciidoctor/asciidoctor-intellij-plugin#131]
Hello, 

with the JavaFxView, Intellj IDEA 15.06 and JDK 8 (64bit) every time I close a .adoc file this happens: 

`null
java.lang.AbstractMethodError
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.disposeComposite(FileEditorManagerImpl.java:1677)
	at com.intellij.openapi.fileEditor.impl.EditorWindow$3.run(EditorWindow.java:244)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runChange(FileEditorManagerImpl.java:1707)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.java:221)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$7.run(FileEditorManagerImpl.java:612)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:608)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:621)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$CloseTab.actionPerformed(EditorTabbedContainer.java:453)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.ui.tabs.impl.ActionButton.actionPerformed(ActionButton.java:113)
	at com.intellij.ui.InplaceButton$1.execute(InplaceButton.java:67)
	at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.execute(BaseButtonBehavior.java:158)
	at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.mouseReleased(BaseButtonBehavior.java:141)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by ahus1** [comment]
I confirm that this happens with IDEA 15.06. The bug does not appear with Version 2016.2

Any chance for you to upgrade to the latest version of IntelliJ IDEA?

**Comment by ahus1** [comment]
The release 0.14.2 is available from the [releases tab](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/tag/0.14.2) of this GitHub repository (but not on the IntelliJ Plugin repository yet). 

Please download and install it manually. Please confirm that this fixes your problem with IntelliJ 15. 

I wonder what IntelliJ versions we should support in the future. 

@Matthias-Ni - do you plan to upgrade to IntelliJ 2016?

**Comment by Matthias-Ni** [comment]
Hello thank you very much for looking into this. I'm on vacation for 2 weeks but I will check it right after I'm back. 

I can't say how long it will take is to update to the latest Intellij version. We got this version 2 month ago and our company is rather slow in updating...

So it would be awesome if you would support 2 major versions ;)

**Comment by ahus1** [comment]
Happy holidays! I'm closing this ticket for now as I tested it before/after the change on IntelliJ 15.

**Comment by DiabolusExMachia** [comment]
Well I'm back and it is working perfectly! Thank you very much for your fix!
