### ISSUE TITLE
Preview stops working after opening a few tabs.

### ISSUE THREAD

**Issue by nvierge** [asciidoctor/asciidoctor-intellij-plugin#1393]
## Observed vs. expected behavior

When the IDE has just been launched, everything works like a charm: the preview is displayed after a slight latency.
After a while and opening several tabs, the preview stops working and remains empty indefinitely.

## Steps to reproduce

1. Start IntelliJ IDEA 2023.1.3 (Community Edition)
2. Open .adoc files in mode "Show Editor and preview"
3. The preview works for a while, then goes blank.

## Environment

Plugin Version: 0.38.20

IntelliJ Details: IntelliJ IDEA 2023.1.3 (Community Edition)
Build #IC-231.9161.38, built on June 20, 2023
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    ide.browser.jcef.gpu.disable=true

Non-Bundled Plugins:
    org.plugin.dot.id (1.4.1)
    PlantUML integration (6.3.0-IJ2022.2)
    org.asciidoctor.intellij.asciidoc (0.38.20)

Kotlin: 231-1.8.21-IJ9161.38

## Logs

```
2023-07-12 08:59:13,966 [  73923]   INFO - STDERR - java.lang.NullPointerException: Cannot invoke "org.cef.handler.CefFocusHandler.onSetFocus(org.cef.browser.CefBrowser, org.cef.handler.CefFocusHandler$FocusSource)" because "this.focusHandler_" is null
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at jcef/org.cef.CefClient.lambda$onSetFocus$1(CefClient.java:467)
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at jcef/com.jetbrains.cef.JdkEx$SyncCallable.run(JdkEx.java:140)
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
2023-07-12 08:59:13,967 [  73924]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
2023-07-12 08:59:13,968 [  73925]   INFO - STDERR - 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
2023-07-12 08:59:13,969 [  73926]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
2023-07-12 08:59:13,969 [  73926]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
2023-07-12 08:59:13,969 [  73926]   INFO - STDERR - 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
2023-07-12 08:59:13,969 [  73926]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
2023-07-12 08:59:13,969 [  73926]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
2023-07-12 08:59:13,969 [  73926]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
2023-07-12 08:59:13,969 [  73926]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
2023-07-12 08:59:13,969 [  73926]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
2023-07-12 08:59:13,969 [  73926]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
2023-07-12 08:59:13,969 [  73926]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-07-12 08:59:15,353 [  75310]   WARN - #org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel - rendering didn't complete in time, might be slow or broken
2023-07-12 08:59:16,098 [  76055]   WARN - #org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel - rendering didn't complete in time, might be slow or broken
2023-07-12 08:59:16,992 [  76949]   WARN - #org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel - rendering didn't complete in time, might be slow or broken
2023-07-12 08:59:18,493 [  78450]   WARN - #org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel - rendering didn't complete in time, might be slow or broken
2023-07-12 08:59:19,234 [  79191]   WARN - #org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel - rendering didn't complete in time, might be slow or broken
2023-07-12 08:59:23,679 [  83636]   WARN - #org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel - rendering didn't complete in time, might be slow or broken
```

**Comment by ahus1** [comment]
I didn't get back on this one in time. If this persists, with a recent version, please let me know.

**Comment by ahus1** [comment]
Closing as there wasn't a comment from the original author.
