### ISSUE TITLE
Slow operations EDT warning when calling element.getUseScope() in AsciiDocScopeEnlarger 

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#1533]
A slow operation warning is logged. 

This started in IU 241.x WRS 233.14272

```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
    at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:101)
    at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:144)
    at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:89)
    at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:247)
    at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:230)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isInTestSourceContent(ProjectFileIndexImpl.java:228)
    at com.intellij.openapi.roots.ProjectRootTestSourcesFilter.lambda$isTestSource$0(ProjectRootTestSourcesFilter.java:12)
    at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:291)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:824)
    at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
    at com.intellij.openapi.roots.ProjectRootTestSourcesFilter.isTestSource(ProjectRootTestSourcesFilter.java:12)
    at com.intellij.openapi.roots.TestSourcesFilter.isTestSources(TestSourcesFilter.java:31)
    at com.intellij.psi.impl.file.impl.ResolveScopeManagerImpl.getUseScope(ResolveScopeManagerImpl.java:207)
    at com.intellij.psi.impl.PsiImplUtil.getMemberUseScope(PsiImplUtil.java:373)
    at com.intellij.psi.impl.source.PsiFieldImpl.getUseScope(PsiFieldImpl.java:413)
    at org.asciidoc.intellij.indexer.AsciiDocScopeEnlarger.getAdditionalUseScope(AsciiDocScopeEnlarger.java:16)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.getUseScope(PsiSearchHelperImpl.java:94)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.getUseScope(PsiSearchHelperImpl.java:78)
    at com.intellij.psi.search.searches.ReferencesSearch$SearchParameters.getEffectiveSearchScope(ReferencesSearch.java:97)
    at com.intellij.psi.impl.search.CachesBasedRefSearcher.processQuery(CachesBasedRefSearcher.java:54)
    at com.intellij.psi.impl.search.CachesBasedRefSearcher.processQuery(CachesBasedRefSearcher.java:19)
    at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:76)
    at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:30)
    at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
    at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:100)
    at com.intellij.util.MergeQuery.processResults(MergeQuery.java:22)
    at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
    at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:100)
    at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:37)
    at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
    at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
    at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:24)
    at com.intellij.util.Query.iterator(Query.java:127)
    at com.intellij.util.AbstractQuery.iterator(AbstractQuery.java:34)
    at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:2054)
    at com.intellij.refactoring.changeSignature.CallerChooserBase.findElementsToHighlight(CallerChooserBase.java:175)
    at com.intellij.refactoring.changeSignature.CallerChooserBase.updateEditorTexts(CallerChooserBase.java:156)
    at com.intellij.refactoring.changeSignature.CallerChooserBase$1.lambda$valueChanged$0(CallerChooserBase.java:110)
    at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
    at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
    at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
    at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
    at com.intellij.util.Alarm$Request.lambda$runSafely$0(Alarm.java:369)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
    at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
    at com.intellij.util.Alarm$Request.run(Alarm.java:356)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
    at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
    at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
    at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:206)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:804)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:422)
    at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:140)
    at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:131)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1126)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
    at java.awt.EventQueue$4.run(EventQueue.java:728)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.security.AccessController.doPrivileged(AccessController.java:400)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:703)
    at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:596)
    at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:107)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:596)
    at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
    at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1026)
    at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
    at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1026)
    at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
    at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:206)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:804)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
    at java.security.AccessController.doPrivileged(AccessController.java:319)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
    at java.awt.Dialog.show(Dialog.java:1079)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:894)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:474)
    at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1754)
    at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1703)
    at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1717)
```

**Comment by ahus1** [comment]
Asked in community support slack: https://jetbrains-platform.slack.com/archives/C5U8BM1MK/p1707335900714709

**Comment by ahus1** [comment]
Issue created: https://youtrack.jetbrains.com/issue/IDEA-345443

**Comment by ahus1** [comment]
Closing due to inactivity in upstream, let's live with the workaround
