### ISSUE TITLE
ruby error in 0.41.11

### ISSUE THREAD

**Issue by htl-leonding** [asciidoctor/asciidoctor-intellij-plugin#1587]
## Observed vs. expected behavior

Wanted to render a asciidoctor document to html

error occurs

2024-03-27 20:20:00,198 [  36451] SEVERE - org.asciidoctor.jruby.internal.JRubyAsciidoctor - (NameError) asciidoctor: FAILED: /Users/xxx/Desktop/abgabe/2324-5bhitm-itp/07-exam3-inventory-2024-03-27-1924/06-exam3-inventory-agh/README.adoc: Failed to load AsciiDoc document - uninitialized constant AsciidoctorExtensions::KrokiDiagram::Base64
2024-03-27 20:20:00,198 [  36451]   WARN - #org.asciidoc.intellij.AsciiDocWrapper - unable to render AsciiDoc document
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NameError: (NameError) asciidoctor: FAILED: /Users/xxx/Desktop/abgabe/2324-5bhitm-itp/07-exam3-inventory-2024-03-27-1924/06-exam3-inventory-agh/README.adoc: Failed to load AsciiDoc document - uninitialized constant AsciidoctorExtensions::KrokiDiagram::Base64
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:412)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:426)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:421)
	at org.asciidoc.intellij.AsciiDocWrapper.convertTo(AsciiDocWrapper.java:955)
	at org.asciidoc.intellij.actions.asciidoc.CreateHtmlAction.lambda$actionPerformed$1(CreateHtmlAction.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:258)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:518)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jruby.exceptions.NameError: (NameError) asciidoctor: FAILED: /Users/xxx/Desktop/abgabe/2324-5bhitm-itp/07-exam3-inventory-2024-03-27-1924/06-exam3-inventory-agh/README.adoc: Failed to load AsciiDoc document - uninitialized constant AsciidoctorExtensions::KrokiDiagram::Base64
	at RUBY.load(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/load.rb:104)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/convert.rb:78)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/convert.rb:190)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1197)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/convert.rb:190)
Caused by: org.jruby.exceptions.NameError: (NameError) uninitialized constant AsciidoctorExtensions::KrokiDiagram::Base64
	at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:4331)
	at RUBY.encode(<script>:299)
	at RUBY.get_diagram_uri(<script>:295)
	at RUBY.create_image_src(<script>:246)
	at RUBY.process(<script>:181)
	at RUBY.process(<script>:33)
	at org.jruby.RubyMethod.call(org/jruby/RubyMethod.java:146)
	at RUBY.build_block(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/parser.rb:1065)
	at RUBY.next_block(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/parser.rb:916)
	at RUBY.next_section(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/parser.rb:403)
	at RUBY.next_section(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/parser.rb:388)
	at RUBY.next_section(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/parser.rb:388)
	at RUBY.parse(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/parser.rb:103)
	at RUBY.parse(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/document.rb:538)
	at RUBY.load(uri:classloader:/gems/asciidoctor-2.0.22/lib/asciidoctor/load.rb:84)
	... 4 more
2024-03-27 20:20:00,219 [  36472] SEVERE - org.asciidoctor.jruby.internal.JRubyAsciidoctor - org.jruby.RubyNameError

## Steps to reproduce

click on html-button

## Environment

Plugin Version: ____0.41.11

IntelliJ Details: ____IntelliJ IDEA 2023.3.6 (Ultimate Edition)
Build #IU-233.15026.9, built on March 21, 2024
Subscription is active until April 17, 2024.
For educational use only.
Runtime version: 17.0.10+1-b1087.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  some.awesome (1.15)
  com.jetbrains.space (233.15026.16)
  org.nik.presentation-assistant (1.0.10)
  io.github.tgeng.latexsymbol.LatexSymbol (0.3)
  com.aegamesi.java_visualizer.plugin (2.2.1)
  PlantUML integration (7.7.1-IJ2023.2)
  nl.rubensten.texifyidea (0.9.3)
  org.asciidoctor.intellij.asciidoc (0.41.11)
  com.github.copilot (1.5.1.5285)
  codiumai.codiumai (0.7.27)
  com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.15.0)
Kotlin: 233.15026.9-IJ

**Comment by ahus1** [comment]
Thank you for reporting this. This seems to be a duplicate of #1585. I will publish a pre-release later today. Please follow that other issue for updates.
