### ISSUE TITLE
IndexOutOfBoundsException when clicking "Title" on empty document

### ISSUE THREAD

**Issue by konfilios** [asciidoctor/asciidoctor-intellij-plugin#166]
## Environment

AsciiDoc Plugin Version: 0.17.2
IDE Name and Version: IntelliJ IDEA 2016.3.1
Build #IC-163.9166.29, built on December 9, 2016
JRE: 1.8.0_112-release-408-b2 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

## Steps

1. Create empty adoc file
1. Before anything else, click on the "Title" button
1. Exception is thrown

## Stack trace

```
chars sequence.length:0, start:0, end:1
java.lang.IndexOutOfBoundsException: chars sequence.length:0, start:0, end:1
	at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:34)
	at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:232)
	at com.intellij.openapi.editor.impl.DocumentImpl$5.compute(DocumentImpl.java:838)
	at com.intellij.openapi.editor.impl.DocumentImpl$5.compute(DocumentImpl.java:835)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:895)
	at com.intellij.openapi.editor.impl.DocumentImpl.getText(DocumentImpl.java:835)
	at org.asciidoc.intellij.actions.asciidoc.FormatAsciiDocAction.isWord(FormatAsciiDocAction.java:58)
	at org.asciidoc.intellij.actions.asciidoc.FormatAsciiDocAction.actionPerformed(FormatAsciiDocAction.java:40)
	at org.asciidoc.intellij.toolbar.AsciiDocToolbarPanel.executeAction(AsciiDocToolbarPanel.java:78)
	at org.asciidoc.intellij.toolbar.AsciiDocToolbarPanel$1.hyperlinkActivated(AsciiDocToolbarPanel.java:66)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:28)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:188)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:121)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ahus1** [comment]
Thanks for reporting this. It will be fixed in the next patch release. Until then please avoid the formatting actions at the begin and end of the document.

**Comment by ahus1** [comment]
Version 0.17.3 is now available from github releases and from jetbrains plugin repository. Please re-open the issue if you still experience a problem.
