### ISSUE TITLE
Line must be non negative: -8

### ISSUE THREAD

**Issue by dodalovic** [asciidoctor/asciidoctor-intellij-plugin#169]
AsciiDoc Plugin Version: `0.17.3`
IDE Name and Version:

```
IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017

JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

```
line must be non negative: -8
java.lang.IllegalArgumentException: line must be non negative: -8
	at com.intellij.openapi.editor.LogicalPosition.<init>(LogicalPosition.java:147)
	at com.intellij.openapi.editor.LogicalPosition.<init>(LogicalPosition.java:114)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel$JavaPanelBridge.lambda$scollEditorToLine$1(JavaFxHtmlPanel.java:356)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ahus1** [comment]
@dodalovic - can you post the contents of _README.adoc_ here, or send them via private mail? This way I could use it as a test case.

**Comment by dodalovic** [comment]
@ahus1 Unfortunately - I can't remember which one that was (I've got couple of projects I switch throughout the day, and also - information there is confidential and not shareable). My assumption is that it might have to do something with `include::` directive.

**Comment by ahus1** [comment]
I think I found the issue, will be available in next release.
