### ISSUE TITLE
Plug-in freezes IntelliJ IDEA 2017.1

### ISSUE THREAD

**Issue by CrazyCoder** [asciidoctor/asciidoctor-intellij-plugin#172]
https://youtrack.jetbrains.com/issue/IDEA-170545

User reports: Opened Settings via ctrl+alt+s, typed "plugins" and it froze forever.

```
    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
    at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
    at org.jruby.ast.ReturnNode.interpret(ReturnNode.java:92)
    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112)
    at org.jruby.gen.InterfaceImpl912978915.convert(org/jruby/gen/InterfaceImpl912978915.gen:13)
    at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:310)
    at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:64)
    at org.asciidoc.intellij.editor.AsciiDocPreviewEditor$2.run(AsciiDocPreviewEditor.java:98)
    at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:59)
```

**Comment by ahus1** [comment]
While the IDE is blocked by Asciidoctor, Asciidoctor is blocked when writing to console (file?)

```
"ApplicationImpl pooled thread 1208" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.PrintStream.write(PrintStream.java:482)
	at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458)
```

I'm not sure why this happend. Maybe disk full? Or a redirection mechanism of the IDE?

The next version will redirect the output of Asciidoctor and write a notification.

**Comment by CrazyCoder** [comment]
Could it be the same issue as described at https://youtrack.jetbrains.com/issue/IDEA-168817#comment=27-2071790? Was IntelliJ IDEA started from the Toolbox App?

**Comment by ahus1** [comment]
@CrazyCoder - this sounds like someone has blocked the console and it could be same issue. But the stack traces look a bit different.

But I am unable to tell if IntelliJ has been started from the Toolbox App. You might need to direct that question to the original reporter of the ticket.
