### ISSUE TITLE
IntelliJ freezes using JavaFX WebView

### ISSUE THREAD

**Issue by marcschumacher** [asciidoctor/asciidoctor-intellij-plugin#177]
**AsciiDoc Plugin Version:** 
0.18.1

**IDE Name and Version:** 
IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

**Description:**
When opening quite long and complex Asciidoctor files (about 700 lines), IntelliJ freezes and I am unable to gain back control (basically I didn't wait indefinitely, but already quite long).
This problem seem to have something to do with the JavaFX view, because when I change back to Swing preview, it works pretty well.

In the freeze thread dump (inside the IntelliJ log folder, I can find the following stacktrace obviously of the "stuck" thread that caused the issue:

```
"AWT-EventQueue-0 2017.1.1#IU-171.4073.35 IDEA, eap:false, os:Mac OS X 10.12.4, java-version:JetBrains s.r.o 1.8.0_112-release-736-b16" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
	at com.sun.glass.ui.mac.MacApplication._runLoop(Native Method)
	at com.sun.glass.ui.mac.MacApplication.runLoop(MacApplication.java:83)
	at com.sun.glass.ui.Application.run(Application.java:153)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel$2.run(JavaFxHtmlPanel.java:122)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

As the file I am working on which causes the problems contains confidential company information, I cannot post the file itself for you to test, but I will try to extract the things that cause the issue and put it into this ticket.

**Comment by ahus1** [comment]
Hello Marc,

these freezes are hard to come by, but I've managed before. But I need some more information.

Could you please send the complete thread dump? You can send it via personal eMail (it's in my GitHub profile). 

If you don't trust the thread dumps created by the freeze detection, you can have a look at https://intellij-support.jetbrains.com/hc/en-us/articles/206544899-Getting-a-thread-dump-when-IDE-hangs-and-doesn-t-respond

Please also send (an excerpt) of the general intellij log (via Help | Show Log in xxx) - https://intellij-support.jetbrains.com/hc/en-us/articles/207241085 

While IntelliJ writes logs entries to this file, you will not see what it writes to the console. I found this helpful when I debugged some JavaFX issue that crashed (not freezed) my IDE. How to do this is also listed under "Thread dump from the console"  https://intellij-support.jetbrains.com/hc/en-us/articles/206544899-Getting-a-thread-dump-when-IDE-hangs-and-doesn-t-respond

**Comment by bodiam** [comment]
Hi @ahus1 ,

I've encountered the same (or similar) issue. I'm not sure since which version is it, but I'm also using the JavaFX view. It seems like IntelliJ is executing a few (at least 2) background tasks at the same time, and then gets stuck in a deadlock. 

I'll try to send you a stackdump when it happens again.

**Comment by ahus1** [comment]
I need more information to follow up on this. 

I'm closing it for now. Please re-open once more information is available.
