### ISSUE TITLE
line must be non negative: -3008

### ISSUE THREAD

**Issue by drosowski** [asciidoctor/asciidoctor-intellij-plugin#179]
AsciiDoc Plugin Version: 0.18.1
IDE Name and Version: 
IntelliJ IDEA 2017.1.2
Build #IU-171.4249.39, built on April 25, 2017
JRE: 1.8.0_112-release-736-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

I just got the following error when previewing an asciidoc document:
`line must be non negative: -3008
java.lang.IllegalArgumentException: line must be non negative: -3008
	at com.intellij.openapi.editor.LogicalPosition.<init>(LogicalPosition.java:148)
	at com.intellij.openapi.editor.LogicalPosition.<init>(LogicalPosition.java:115)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel$JavaPanelBridge.lambda$scollEditorToLine$1(JavaFxHtmlPanel.java:358)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by ahus1** [comment]
@drosowski I suppose this error message appeared when you clicked in the preview window to place the cursor. Can you please post the document you used (or prepare a minimal document) and describe where you clicked?

**Comment by ahus1** [comment]
Example needed. Closing it for now.

**Comment by bric3** [comment]
I see similar errors.

```
line must be non negative: -726
java.lang.IllegalArgumentException: line must be non negative: -726
	at com.intellij.openapi.editor.LogicalPosition.<init>(LogicalPosition.java:170)
	at com.intellij.openapi.editor.LogicalPosition.<init>(LogicalPosition.java:131)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel$JavaPanelBridge.lambda$scollEditorToLine$0(JavaFxHtmlPanel.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Unfortunately I cannot disclose the content of the document and I wasn't able to reproduce the issue with minimal document. I can however 

The outline of the document is as follow : 

index.adoc

```
:doctype: book
:icons: font
:source-highlighter: coderay
:toc: left
:toclevels: 4
:sectlinks:
:sectanchors:

// allows to see snippets in IDEA, overriden by gradle task
:snippets: {docdir}/../../../build/generated-snippets

:black_logo: images/black-logo.png

image:{black_h_bbc_logo}[]

= Big Title
Doc authors;

include::./introduction.adoc[leveloffset=+1]

include::./principles.adoc[leveloffset=+1]

include::./endpoints.adoc[leveloffset=+1]
```

principles.adoc

```
= Title of principles

== Title A level 2

include::./diagrams/some_plantuml_sequence_diagram.adoc[]

== Title B level 2

include::./diagrams/some_plantuml_sequence_diagram.adoc[]

```

endpoints.adoc

```
= Endpoints

== Greek letters

include::./endpoints/aplha.adoc[leveloffset=+2]
include::./endpoints/beta.adoc[leveloffset=+2]
include::./endpoints/gamma.adoc[leveloffset=+2]
// many more includes

== ...

// includes

```
