### ISSUE TITLE
Editor crashes when editing a string fragment

### ISSUE THREAD

**Issue by wsidl** [asciidoctor/asciidoctor-intellij-plugin#194]
Plugin crashes when prompted to edit an Asciidoc Fragment in PyCharm.

Completed the following steps:
1. Create DocString for Python Module file.
2. Write AsciiDoc markup text into DocString
3. Inject AsciiDoc Language Reference into DocString
	- AsciiDoc Syntax Highlighting activated.
4. PyCharm context alert prompted to "Edit AsciiDoc Fragment". Selected option from context menu.
5. Preview window started to appear in editor, error occured during setup.
	- Typing this error report with split window behind the dialog, but no content in window.

## Stacktrace
null
java.lang.NullPointerException
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel.<init>(JavaFxHtmlPanel.java:104)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanelProvider.createHtmlPanel(JavaFxHtmlPanelProvider.java:20)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.detachOldPanelAndCreateAndAttachNewOne(AsciiDocPreviewEditor.java:229)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.<init>(AsciiDocPreviewEditor.java:189)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditorProvider.createEditor(AsciiDocPreviewEditorProvider.java:59)
	at org.asciidoc.intellij.ui.SplitTextEditorProvider$2.build(SplitTextEditorProvider.java:137)
	at org.asciidoc.intellij.ui.SplitTextEditorProvider$1.build(SplitTextEditorProvider.java:62)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:860)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2781)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManage

AsciiDoc Plugin Version: 0.19.0

IDE Name and Version: PyCharm 2017.2.1
Build #PY-172.3544.46, built on August 9, 2017
...
JRE: 1.8.0_152-release-915-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by ahus1** [comment]
Thanks for reporting this with an accurate description and all necessary details. 

I fixed this bug and it will be available in the next release of the plugin.

**Comment by ahus1** [comment]
This is now available in release 0.19.2. You can download it from [the release page](https://github.com/asciidoctor/asciidoctor-intellij-plugin). Please comment if it works for you.
