### ISSUE TITLE
Preview not showing

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-intellij-plugin#200]
For some time the preview haven't been working. I suspect since last IntelliJ update, but can't be 100% sure.
When using FX the preview panel stays white showing the text "Initializing...", the Swing preview just stays white.
I check IntelliJ's logs directory I only saw this, which I think is unrelated (see below, it's a Connection reset by peer). Is there any other log or place to get info on what could possible be happening?

```
2018-01-09 08:44:01,439 [3292236]   INFO - .server.BuildMessageDispatcher - Se ha forzado la interrupción de una conexión existente por el host remoto 
java.io.IOException: Se ha forzado la interrupción de una conexión existente por el host remoto
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

**AsciiDoc Plugin Version**
 0.19.2

**IDE Name and Version**
IntelliJ IDEA 2017.3.2 (Community Edition)
Build #IC-173.4127.27, built on December 25, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by abelsromero** [comment]
I am closing because I haven't seen the issue lately. Maybe something wrong in my machine.
