### ISSUE TITLE
Plugin does not interpret document links correctly

### ISSUE THREAD

**Issue by twogee** [asciidoctor/asciidoctor-intellij-plugin#204]
Plugin opens `link:file{outfilesuffix}` as `file.html/` in a browser rather than `file.adoc` in the IDE.

AsciiDoc Plugin Version: 0.20

IDE Name and Version: IntelliJ IDEA 2017.3.5 (Community Edition)

**Comment by ahus1** [comment]
Links are currently not supported - neither in preview now in the editor. I'd be happy for a pull request.

**Comment by ahus1** [comment]
There is now a pre-release 0.26.4 available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases).

Thanks to PR #256 by @bbrenne, clicking on a link the preview on the right will lead to the referenced AsciiDoc file. The work to make references clickable in the editor continues in this ticket.

The follow type of references work: 

```
<<reffile#id>>

link:reffile.adoc[]

link:reffile.html[]

link:reffile[]

link:reffile.adoc#id[]

link:reffile.html#id[]

link:reffile#id[]
```

Please give it a try. If this works for you, or if you experience problems, please leave a comment in this issue.

**Comment by twogee** [comment]
Thanks, great work! I was testing `link:file{outfilesuffix}` style links, and everything looked peachy, but after opening several documents by following links in 2019.1.2, I got an exception
```
Details: Current thread: Thread[AWT-AppKit,5,system] 778461896
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1506683917

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1087)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:358)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:160)
	at org.asciidoc.intellij.psi.AsciiDocUtil.findIds(AsciiDocUtil.java:41)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel$JavaPanelBridge.openInEditor(JavaFxHtmlPanel.java:467)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel$JavaPanelBridge.openLink(JavaFxHtmlPanel.java:429)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.webkit.Utilities.lambda$fwkInvokeWithContext$0(Utilities.java:60)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.webkit.Utilities.fwkInvokeWithContext(Utilities.java:60)
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:807)
	at javafx.scene.web.WebView.processMouseEvent(WebView.java:1045)
	at javafx.scene.web.WebView.lambda$registerEventHandlers$3(WebView.java:1168)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$null$4(EmbeddedScene.java:258)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$5(EmbeddedScene.java:244)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by ahus1** [comment]
@twogee - thank you for providing the full exception, this helped to analyse the issue. I wasn't able to reproduce it locally, but I've now implemented the mechanism the exception point to. 

There is now a pre-release 0.26.5 available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) that should remedy this issue.

Please give it a try. If this works for you, or if you experience problems, please leave a comment in this issue.

**Comment by twogee** [comment]
Thank you for prompt response.  The plugin works faultlessly. 👍
