### ISSUE TITLE
IllegalArgumentException: line must be non negative

### ISSUE THREAD

**Issue by Nowheresly** [asciidoctor/asciidoctor-intellij-plugin#212]
AsciiDoc Plugin Version: 0.20.6

IDE Name and Version: IntelliJ 2018.2 build 24 july 2018

Hi,

I'm getting this exception from times to times when I resize the javaFX pane.

java.lang.IllegalArgumentException: line must be non negative: -323
	at com.intellij.openapi.editor.LogicalPosition.<init>(LogicalPosition.java:105)
	at com.intellij.openapi.editor.LogicalPosition.<init>(LogicalPosition.java:101)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel$JavaPanelBridge.lambda$scollEditorToLine$0(JavaFxHtmlPanel.java:404)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ahus1** [comment]
There is a new [pre-release 0.21.0](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) available that will no longer show this as a big exception, but a small warning. 

I hope this defuses it a bit. Please give it a try. You will also have the very latest version of AsciidoctorJ and JRuby included - this might behave differently in some places. I'm looking for testers for this new version.
