### ISSUE TITLE
Plugin crash on startup in Android Studio 3.2.1

### ISSUE THREAD

**Issue by jmfayard** [asciidoctor/asciidoctor-intellij-plugin#226]
AsciiDoc Plugin Version: 0.21.4

IDE Name and Version: Android Studio 3.2.1

```
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

The plugin is unusable, it crash on an empty `README.adoc` file with the error `Factory already defined` 

Stacktrace: 

```
factory already defined
java.lang.Error: factory already defined
	at java.net.URL.setURLStreamHandlerFactory(URL.java:1112)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanelProvider.<clinit>(JavaFxHtmlPanelProvider.java:16)
	at org.asciidoc.intellij.settings.AsciiDocPreviewSettings.<init>(AsciiDocPreviewSettings.java:32)
	at org.asciidoc.intellij.settings.AsciiDocPreviewSettings.<clinit>(AsciiDocPreviewSettings.java:20)
	at org.asciidoc.intellij.settings.AsciiDocApplicationSettings$State.<init>(AsciiDocApplicationSettings.java:55)
	at org.asciidoc.intellij.settings.AsciiDocApplicationSettings.<init>(AsciiDocApplicationSettings.java:22)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:240)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:207)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:39)
	at org.asciidoc.intellij.settings.AsciiDocApplicationSettings.getInstance(AsciiDocApplicationSettings.java:26)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.<init>(AsciiDocPreviewEditor.java:201)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditorProvider.createEditor(AsciiDocPreviewEditorProvider.java:59)
	at org.asciidoc.intellij.ui.SplitTextEditorProvider$2.build(SplitTextEditorProvider.java:137)
	at org.asciidoc.intellij.ui.SplitTextEditorProvider$1.build(SplitTextEditorProvider.java:62)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$9(FileEditorManagerImpl.java:850)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:643)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:656)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:947)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:776)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$4(FileEditorManagerImpl.java:758)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:95)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:71)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:758)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:689)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:155)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openEditor$11(FileEditorManagerImpl.java:1104)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:137)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:95)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:71)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1102)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInAnyFileEditor(OpenFileDescriptor.java:145)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditor(OpenFileDescriptor.java:131)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditorOrNativeApp(OpenFileDescriptor.java:127)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:114)
	at com.intellij.psi.impl.source.PsiFileImpl.navigate(PsiFileImpl.java:986)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:192)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:227)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:63)
	at com.intellij.ui.AutoScrollToSourceHandler.lambda$null$2(AutoScrollToSourceHandler.java:201)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.ui.AutoScrollToSourceHandler.lambda$scrollToSource$3(AutoScrollToSourceHandler.java:180)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ui.AutoScrollToSourceHandler.scrollToSource(AutoScrollToSourceHandler.java:180)
	at com.intellij.ui.AutoScrollToSourceHandler.lambda$onMouseClicked$0(AutoScrollToSourceHandler.java:146)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ahus1** [comment]
Hi, there seems to be a conflicting plugin installed that uses URL.setURLStreamHandlerFactory() like we do in this plugin. 

I can work around the conflict that there is no exception, but still the refresh of images will work in the JavaFX preview.

Do you use a plugin that uses a HTML-like preview? Could you please list the plugins you used in this ticket? 

Thanks!

**Comment by jmfayard** [comment]
You are right. That's one of the plugins I disabled here

![image](https://user-images.githubusercontent.com/459464/48180455-dadbd280-e323-11e8-833d-b46a8328fa3b.png)

**Comment by ahus1** [comment]
Thanks for posting the list. I'm not sure how to read this list: 
* Did you disable one or more plugins and now it works? 
* Which of the plugins do you think might cause it?

**Comment by jmfayard** [comment]
@ahu1
> Did you disable one or more plugins and now it works?

yes

>  Which of the plugins do you think might cause it?

I can now reproduce it: 

The one plugin that is causing the conflict is `Fabric for Android Studio`.

**Comment by ahus1** [comment]
This available in 0.22.0. As this is still a pre-release (and it contains other experimental features) is available only from the [GitHub releases page](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) of this project.
