### ISSUE TITLE
Shortcuts for bold, italic, strikethrough, etc.

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctor-intellij-plugin#242]
This plugin is already quite usable, but I do miss sometime to be able to quickly style text using a shortcut. I have two complementary approaches, one using shortcuts like <kbd>cmd</kbd>+<kbd>b</kbd> or using some characters like <kbd>*</kbd> to surround the selection.

Let's imagine these situations : 

1. With selected text

   ```
   <start of selection>lorem ipsum<end of selection>
   ```
   a. press <kbd>cmd</kbd>+<kbd>b</kbd> to make this selection bold.

   b. press <kbd>*</kbd> to toggle surround the text with `*`.  I don't know if it is easy to integrate this within IJ or not. 

   Eventually the tool will be smart enough to inserts double `*` to make the style unconstrained if any selection boundaries are within a word.

2. Nothing is selected

   ```
   lorem <cursor position>
   ```
   press <kbd>cmd</kbd>+<kbd>b</kbd> to open a bold _span_ (`lorem *<cursor position>*`). Possibly press <kbd>cmd</kbd>+<kbd>b</kbd> again to open an unconstrained _span_ (`lorem **<cursor position>**`). Pressing <kbd>cmd</kbd>+<kbd>b</kbd> a third time will remove the surrounding stars `*` (`lorem <cursor position>`)

-----

I know that IJ have smart keys for some characters, but I don't know if it is extensible depending on the document/file type.

![Screen Shot 2019-03-27 at 12 11 09](https://user-images.githubusercontent.com/803621/55071695-97db8b00-5089-11e9-978d-2137249e5c75.png)

**Comment by bric3** [comment]
For reference I just remembered that I opened an issue on this topic https://youtrack.jetbrains.com/issue/IDEA-176569 like 2 years.

**Comment by ahus1** [comment]
@bric3 - here a short summary of the current state of the functionality:

1. You can change bold/mono/italic from the editors toolbar for pre-selected. These actions are also available "Find Action | Bold", there you can use "Alt | Return" to assign a shortcut.
These actions will select the current word if you haven't selected a text before. 
Currently there is no pre-defined shortcut. 

2. These actions are already smart enough to add a constrained or unconstrained formatting. 

Adding handling for brackets and quotes could be relatively straight-forward once the parsing is in place for them using the AsciiDocBraceMatcher. 

Making this work for bold/mono/italic could involve a typedHandler as defined for example in the JsonPlugin in the community edition of IntelliJ (see https://github.com/JetBrains/intellij-community/blob/master/json/src/com/intellij/json/editor/JsonTypedHandler.java).

**Comment by bric3** [comment]
@ahus1 Thanks

1. Hi thanks I was unaware of these actions that could be bound in the keymap settings. However, the Cmd+B, and close combinations like Alt, or Ctrl or Shift are mostly already set. But the way it looks I think that IJ cannot set a shortcut that is already set in the context of another editor like Asciidoc.

2. OK :)

3. Ah ok 0.26.8 is not yet published as of now (https://plugins.jetbrains.com/plugin/7391-asciidoc). Eager to look at it.

Thanks for the code pointer !

**Comment by ahus1** [comment]
On the github releases page there are pre-releases. You might want to give them a try: [Github Releases tab](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) 

As always, feedback is welcome.

**Comment by ahus1** [comment]
@bric3 - I've looked at your suggestion again today and made some improvements. 

The expand-selection using Ctrl-W will be more fine-grained and works on word/line level. Once you've selected some text, you can toggle its formatting using the formatting keys "/", "`", "*" and "_". 

These improvements are not released yet. I'll update this ticket once a pre-release is ready.

Here's a short recording of pressing Ctrl-W first, then * and _ to toggle the formatting of the text.

![format_using_keys](https://user-images.githubusercontent.com/3957921/67162487-b4f8e380-f364-11e9-97d3-2fb92c85e579.gif)

(cc: @Mogztter, I think you've asked for something similar some weeks ago)

**Comment by Mogztter** [comment]
Yes I look forward to give it a try!

**Comment by ahus1** [comment]
This is part of pre-release 0.30.12. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by bric3** [comment]
This is great, thanks a lot !!!

-- Brice

**Comment by bric3** [comment]
While the functionality works well, I regularly see this error in the error report

```
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key editor.smarterSelectionQuoting
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:112)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:172)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:156)
	at com.intellij.openapi.util.registry.RegistryValue.calcBoolean(RegistryValue.java:64)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:57)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:47)
	at org.asciidoc.intellij.actions.FormattingQuotedTypedHandler.beforeSelectionRemoved(FormattingQuotedTypedHandler.java:80)
	at com.intellij.codeInsight.editorActions.TypedHandler.lambda$null$1(TypedHandler.java:173)
	at com.intellij.codeInsight.editorActions.TypedHandler.callDelegates(TypedHandler.java:230)
	at com.intellij.codeInsight.editorActions.TypedHandler.lambda$execute$4(TypedHandler.java:173)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:355)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:457)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:347)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:337)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:152)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:75)
	at com.intellij.codeInsight.template.emmet.EmmetPreviewTypedHandler.execute(EmmetPreviewTypedHandler.java:39)
	at com.intellij.codeInsight.editorActions.AutoFormatTypedHandler.executeOriginalHandler(AutoFormatTypedHandler.java:167)
	at com.intellij.codeInsight.editorActions.AutoFormatTypedHandler.execute(AutoFormatTypedHandler.java:94)
	at com.goide.editor.GoTypedHandler.execute(GoTypedHandler.java:48)
	at com.intellij.execution.impl.ConsoleViewImpl$MyTypedHandler.execute(ConsoleViewImpl.java:1175)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler$1.run(DefaultRawTypedHandler.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:885)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler.execute(DefaultRawTypedHandler.java:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$MyRawTypedHandler.execute(EditorFactoryImpl.java:289)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$0(TypedAction.java:133)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:28)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:133)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1291)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1274)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3349)
	at com.intellij.openapi.editor.impl.EditorImpl$7.keyTyped(EditorImpl.java:1104)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6606)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2849)
	at java.desktop/java.awt.Component.processEvent(Component.java:6428)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:878)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1148)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1017)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:843)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:40)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4907)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:832)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ahus1** [comment]
@bric3 - could you please provide me the version information of you IDE (from menu entry Help | About) and the plugins you use? Looking at the stack trace it seems you have a go plugin installed (or the go IDE)?

**Comment by ahus1** [comment]
@bric3 - can now reproduce it, no need to post further information. Not dependent on IDE.

**Comment by ahus1** [comment]
A new pre-release 0.30.13 is available that fixes the exception @bric3 observed. I failed to test the plugin in an IDE outside my development environment, sorry for that. 

You will see the following change: when toggling the formatting on a selected piece of text, the text will still be selected after the formatting changed. The exception @bric3 saw prevented that.

Please let me know if this work better for you.
