### ISSUE TITLE
Asciidoc preview won't show up / Regression 0.25.9

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#250]
I'm getting this kind of exception on IntelliJ Ultimate 2019.1.1/ Linux with 0.25.9 version of the plugin. The Asciidoc preview won't show up. This happens on all Asciidoc files, so it doesn't seem to be related to the content of the file.
```
java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:475)
	at org.asciidoc.intellij.AsciiDoc.initWithExtensions(AsciiDoc.java:123)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:285)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:280)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor$2.run(AsciiDocPreviewEditor.java:124)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:59)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jruby.util.io.FilenoUtil$ReflectiveAccess
	at org.jruby.util.io.FilenoUtil.getFilenoUsingReflection(FilenoUtil.java:111)
	at org.jruby.util.io.FilenoUtil.filenoFrom(FilenoUtil.java:107)
	at org.jruby.RubyGlobal.prepareStdioChannel(RubyGlobal.java:335)
	at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:298)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:211)
	at org.jruby.Ruby.init(Ruby.java:1260)
	at org.jruby.Ruby.newInstance(Ruby.java:370)
	at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:79)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.createRubyRuntime(JRubyAsciidoctor.java:125)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.<init>(JRubyAsciidoctor.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 14 more
```
As a workaround, I downgraded to 0.24.4 by downloading [asciidoctor.zip](https://plugins.jetbrains.com/files/7391/60081/asciidoctor.zip?updateId=60081&pluginId=7391&family=intellij) from the plugin portal and using the "Install Plugin From Disk..." feature in IntelliJ.

_Originally posted by @lhotari in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/248#issuecomment-488983811_

**Comment by ahus1** [comment]
@lhotari - I moved this to a separate issue to track it here, as it seems to be a regression, but unrelated to the other issue. 

Could you please report also the JDK you use to run IntelliJ? 

go to Help -> About, click on 'Copy to Clipboard' and paste the contents of your clipboard here

Thanks!

**Comment by lhotari** [comment]
@ahus1 here's the versions information:
```
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-48-generic
```

**Comment by mikeholler** [comment]
I'm also having this issue:

```
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
Licensed to Michael Holler
Subscription is active until February 4, 2020
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-48-generic
```

```
java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:475)
	at org.asciidoc.intellij.AsciiDoc.initWithExtensions(AsciiDoc.java:123)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:285)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:280)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor$2.run(AsciiDocPreviewEditor.java:124)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:59)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.headius.backport9.modules.Modules.addOpens(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Class;)V
	at org.jruby.util.io.FilenoUtil$ReflectiveAccess.<clinit>(FilenoUtil.java:140)
	at org.jruby.util.io.FilenoUtil.getFilenoUsingReflection(FilenoUtil.java:111)
	at org.jruby.util.io.FilenoUtil.filenoFrom(FilenoUtil.java:107)
	at org.jruby.RubyGlobal.prepareStdioChannel(RubyGlobal.java:335)
	at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:298)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:211)
	at org.jruby.Ruby.init(Ruby.java:1260)
	at org.jruby.Ruby.newInstance(Ruby.java:370)
	at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:79)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.createRubyRuntime(JRubyAsciidoctor.java:125)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.<init>(JRubyAsciidoctor.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 14 more
```

![Screenshot from 2019-05-03 07-26-13](https://user-images.githubusercontent.com/1164112/57137215-ccbbbb80-6d74-11e9-9c8b-61e4dc8c1cc0.png)

I also did an `Invalidate Caches & Restart` and then did New Project -> Empty Project with one file in it:

![Screenshot from 2019-05-03 07-29-33](https://user-images.githubusercontent.com/1164112/57137343-3936ba80-6d75-11e9-8405-dff85e60b736.png)

Finally, I get a lot of input lag when typing, this may be unrelated, but it also might be the same issue.

**Comment by mikeholler** [comment]
I also pulled the following out of my idea logs:

```
2019-05-03 07:29:32,004 [60365646]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2019.1.1  Build #IU-191.6707.61 
2019-05-03 07:29:32,004 [60365646]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-05-03 07:29:32,004 [60365646]  ERROR - plication.impl.ApplicationImpl - OS: Linux 
2019-05-03 07:29:32,006 [60365648]  ERROR - plication.impl.ApplicationImpl - Plugin to blame: AsciiDoc version: 0.25.9 
2019-05-03 07:29:32,006 [60365648]  ERROR - plication.impl.ApplicationImpl - Last Action: EditorEnter 
2019-05-03 07:29:32,341 [60365983]  ERROR - t.daemon.impl.ExternalToolPass - IdeaLoggingEvent[message=ExternalToolPass: , throwable=com.intellij.diagnostic.PluginException: annotator: org.asciidoc.intellij.annotator.ExternalAnnotator@1d98be5c (class org.asciidoc.intellij.annotator.ExternalAnnotator) [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:368)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:68)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:195)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:41)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:166)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$10(BackgroundTaskUtil.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:263)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:242)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:165)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:336)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:326)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:276)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:290)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:245)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:475)
	at org.asciidoc.intellij.AsciiDoc.initWithExtensions(AsciiDoc.java:123)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:285)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:65)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:35)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:192)
	... 32 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jruby.util.io.FilenoUtil$ReflectiveAccess
	at org.jruby.util.io.FilenoUtil.getFilenoUsingReflection(FilenoUtil.java:111)
	at org.jruby.util.io.FilenoUtil.filenoFrom(FilenoUtil.java:107)
	at org.jruby.RubyGlobal.prepareStdioChannel(RubyGlobal.java:335)
	at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:298)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:211)
	at org.jruby.Ruby.init(Ruby.java:1260)
	at org.jruby.Ruby.newInstance(Ruby.java:370)
	at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:79)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.createRubyRuntime(JRubyAsciidoctor.java:125)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.<init>(JRubyAsciidoctor.java:50)
	at sun.reflect.GeneratedConstructorAccessor888.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 40 more
] 

```

**Comment by ahus1** [comment]
I mixed up the JRuby release packaged in the plugin; I'll provide a fix

**Comment by mikeholler** [comment]
I can also confirm that downgrading the plugin version to 0.24.4 like @ahus1 suggested works for me.

**Comment by ahus1** [comment]
Thank you for providing the exceptions and version information. I've fixed the issue, a new version 0.25.11 is available from GitHub releases and should available via automatic update from the JetBrains plugin repository soon. 

Please git it a try; I haven't been able to reproduce it on Windows, but the error messages look like a JRuby-version-classpath-mixup.

**Comment by mikeholler** [comment]
Thanks so much! I do my best not to expect quick turn-around times from OSS maintainers, especially when a satisfactory workaround exists (falling back to previous version). I really appreciate that you were able to fix this so quickly (and thanks for maintaining this plugin, I use it daily).

**Comment by ahus1** [comment]
@mikeholler - thank you for the fast feedback and the nice comment!
