### ISSUE TITLE
Illegal Agument Exception when handling old style heading

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#274]
When adding a blank at the caret's space, and exception occurs (reported by @bjkastel)

````
<caret>H
+
````

AsciiDoc Plugin Version: 0.28.1

````
Stacktrace:

java.lang.IllegalArgumentException: unknown character '
' in switch
              at org.asciidoc.intellij.parser.AsciiDocParserImpl.headingLevel(AsciiDocParserImpl.java:323)
              at org.asciidoc.intellij.parser.AsciiDocParserImpl.parse(AsciiDocParserImpl.java:92)
              at org.asciidoc.intellij.parser.AsciiDocParser.parse(AsciiDocParser.java:20)
              at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:75)
              at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)

````

**Comment by ahus1** [comment]
This is fixed in 0.28.2 (available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap)).

Thanks for catching this bug while the release was in preview!
