### ISSUE TITLE
NPE on opening existing .adoc with included plantuml after upgrade to 0.28.5

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-intellij-plugin#284]
After upgrading to 0.28.5 (?) I tried to open a file from the arc42 documentation (05_bausteinsicht.adoc) from my current project (which is well known to @ahus1) to test #282 on windows I received and NPE immediately:

```
java.lang.NullPointerException
	at org.asciidoc.intellij.editor.javafx.JavaFxMightBeBlurredNotificationProvider.createNotificationPanel(JavaFxMightBeBlurredNotificationProvider.java:54)
	at org.asciidoc.intellij.editor.javafx.JavaFxMightBeBlurredNotificationProvider.createNotificationPanel(JavaFxMightBeBlurredNotificationProvider.java:22)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:136)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:977)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:225)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:33)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:176)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

AsciiDoc Plugin Version: _____

This is a strange somehow:
* The list of installed plugins does not show the version number:
![image](https://user-images.githubusercontent.com/456000/60260873-d4ae5c80-98da-11e9-8f47-37eb985fe057.png)
* The updates section shows there is an update (to 0.28.5) pending:
![image](https://user-images.githubusercontent.com/456000/60260932-f9a2cf80-98da-11e9-9f41-f5c801f07e17.png)
* According to the marketplace I have 0.28.5 already installed
![image](https://user-images.githubusercontent.com/456000/60260811-b21c4380-98da-11e9-8422-2662e5f0498d.png)
* The log tells me, I am still on 0.28.3: `2019-06-27 12:40:22,092 [ 248523]  ERROR - oncurrency.BoundedTaskExecutor - Plugin to blame: AsciiDoc version: 0.28.3`
* However, I can reproduce the behaviour with 0.28.5 as well ...

IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018
Licensed to Gerd Aschemann
You have a perpetual fallback license for this version
Subscription is active until January 11, 2020
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ascheman** [comment]
I get the same error from other files now when opening them, e.g., `03_kontextabgrenzung.adoc` from the very same arc42 project, even if it does not contain PlantUML.

**Comment by wimdeblauwe** [comment]
Exception happens at this line:

```
if (System.getProperty("sun.java2d.uiScale.enabled").equalsIgnoreCase("false")) {
```

Maybe you can set the `sun.java2d.uiScale.enabled` property as a workaround, but I don't know exactly how to do that.

**Comment by ahus1** [comment]
@ascheman - My mistake, thanks for catching this issue!

@wimdeblauwe - well spotted! will provide a fix soon.

**Comment by ahus1** [comment]
Pre-Release 0.28.6 fixes the error. Could you please give it a try? 

It is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

Regarding the version number: I wasn't able to reproduce it with 2019.1.3. Thank you for looking up the version number from the log.

**Comment by ascheman** [comment]
No NPEs any more, thanks for the fast response!
