### ISSUE TITLE
Browser preview for files outside current project / Asciidoc 0.28.22

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#303]
Stack trace for IntelliJ 2019.2 and Asciidoc 0.28.22

Java.lang.NullPointerException
	at org.asciidoc.intellij.editor.javafx.PreviewStaticServer.lambda$sendDocument$0(PreviewStaticServer.java:180)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at org.asciidoc.intellij.editor.javafx.PreviewStaticServer.sendDocument(PreviewStaticServer.java:178)
	at org.asciidoc.intellij.editor.javafx.PreviewStaticServer.process(PreviewStaticServer.java:134)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:21)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:36)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:11)
	at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:21)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)

![image](https://user-images.githubusercontent.com/13682850/61940329-80f46900-af95-11e9-9ed9-7a490aafd1e4.png)

**Comment by wfouche** [comment]
Whey I click on one of the browser preview button (Chrome, Firefox, etc.)  the following error is displayed in the browser:

![image](https://user-images.githubusercontent.com/13682850/61940619-17288f00-af96-11e9-8677-3ee41f506905.png)

**Comment by ahus1** [comment]
Hi @wfouche - I'm sorry to hear that the new release doesn't work well with the current version of the plugin. 

Unfortunately I can't reproduce the issue locally with IntelliJ 2019.2 and AsciiDoc 0.28.22. Looking at the code I have an idea what is going wrong, but I'll need to know more about the project. 

Some background information: The browser passes the name of the file in the URL. In a loop the plugin iterates over all projects open in the IDE. The project that has the same base path as the file requested is selected and used for rendering. 

It seems that your setup is different, as looping over all open projects doesn't find a project with a base path matching the file opened in the browser. 

I'm considering passing the project as part of the URL, but I'm not sure why the logic above it not working. Can you help me to understand you project setup? Thanks!

**Comment by wfouche** [comment]
@ahus1 Thanks for the quick response. No need to apologize. Asciidoc in IntelliJ is always a joy to use. On another PC that does not have IntelliJ installed, a fresh install of 2019.2 with the latest Asiidoc plug-in works as expected. I'm starting to think that there might just be something wrong in the Windows environment on my other laptop. I'm going to re-install IntelliJ 2019.2 there as well and re-test.  Hopefully, it is not an Asciidoc Plug-in bug.

**Comment by wfouche** [comment]
@ahus1  So far I've only used IntelliJ as a text editor like one would use vi on Linux or Notepad++ on Windows. No projects exist, although I'm planning to create a few in the future. Could this have had something to do with the crash?  My Asciidoc files were simple opened using File / Open and then edited and rendered.

**Comment by wfouche** [comment]
@ahus1 On the machine that I originally encountered the issue on, the issue persists after a re-install of IntelliJ. IntelliJ was not installed, just unzipped to a folder and running the 64bit executable. Then opening an Asciidoc file and edit  / view it. The 404 Not Found error issue was not solved by the re-install, however the crash has not re-occurred yet.

**Comment by ahus1** [comment]
The issue is with the plugin, too bad I wasn't able to reproduce it yet. I've published a pre-release 0.28.24. I studies the API of IntelliJ more closely and there should be a NPE any more.

While opening the preview for regular files, the this change disables opening in-memory-only files in the browser for preview. This happens for example when you use "Edit fragment..." on AsciiDoc content inside other files.

Please install this preview version. 

Please note: if you have already a URL open in your browser this will no longer be valid. Please open the preview again when you starting your IDE.

If the 404 error persists, please have a look at the log file. If there is no additional message, I'll have to add more log statements :-/

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by ahus1** [comment]
> @ahus1 So far I've only used IntelliJ as a text editor like one would use vi on Linux or Notepad++ on Windows. No projects exist, although I'm planning to create a few in the future. Could this have had something to do with the crash? My Asciidoc files were simply opened using File / Open and then edited and rendered.

This was the reason. This should now work as well with 0.28.24+

I assume that after you installed IntelliJ 2019.2 you also updated to the latest version of the plugin. The open-in-browser functionality changed in version 0.28.9. Before that the file was opened in the browser directly and you needed for example the Chrome AsciiDoc plugin to render the contents. Starting with 0.28.9 the browser will show the rendered content of the IDE preview in the browser, see #82. 

If you want to open the file in the browser directly (without using the IDE rendered HTML), please use the "external tool" functionality described in the note of #82.

**Comment by wfouche** [comment]
@ahus1 I'm very happy to report that 0.28.24 resolves the issue! Thanks, again for responding so quickly to this issue. Much appreciated.

**Comment by ahus1** [comment]
Although the browser preview works only on localhost, I've tightened up the security; the file name needs to come with the IDE as it will be signed with a MAC, and the key will change whenever you restart the IDE. Therefore showing a file in the preview will only work by opening this specific file in from the IDE in the preview. This is part of release 0.28.25 that I'll publish within the next minutes.

**Comment by wfouche** [comment]
Tested the new 0.28.25 release, and it works flawlessly (as far as I can tell).
