### ISSUE TITLE
Error in IntelliJ 2019.2 if plugin in /plugins folder of IntelliJ-installation

### ISSUE THREAD

**Issue by chwoerz** [asciidoctor/asciidoctor-intellij-plugin#309]
I've installed the newest version of asciidoctor(0.28.25) in IntelliJ 2019.2. After this installation, I've moved the plugin from the default install-directory where additional plugins are normally installed , into the intellijroot/plugins folder, because I need to bundle the installation with the plugins. I've already done this in previous IntelliJ versions, and it worked without any problem.

The plugin gets recognized by IntelliJ in the plugin-settings page, but the following error occurs in the log. In my opinion, this happens, because the plugin wants to use the old path instead of using intellijroot/plugins
```
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: While loading class org.asciidoc.intellij.builder.AsciiDocTargetScopeProvider: com/intellij/compiler/impl/BuildTargetScopeProvider [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:50)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:54)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:439)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:410)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:244)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:34)
	at com.intellij.compiler.impl.CompileDriver.mergeScopesFromProviders(CompileDriver.java:194)
	at com.intellij.compiler.impl.CompileDriver.getBuildScopes(CompileDriver.java:186)
	at com.intellij.compiler.impl.CompileDriver.compileInExternalProcess(CompileDriver.java:207)
	at com.intellij.compiler.impl.CompileDriver.lambda$isUpToDate$0(CompileDriver.java:116)
	at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressInCurrentThread(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:305)
	at com.intellij.openapi.progress.Task.queue(Task.java:115)
	at com.intellij.compiler.progress.CompilerTask.start(CompilerTask.java:414)
	at com.intellij.compiler.impl.CompileDriver.isUpToDate(CompileDriver.java:110)
	at com.intellij.compiler.CompilerManagerImpl.isUpToDate(CompilerManagerImpl.java:262)
	at com.intellij.compiler.backwardRefs.CompilerReferenceServiceBase.lambda$projectOpened$2(CompilerReferenceServiceBase.java:111)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.diagnostic.PluginException: While loading class org.asciidoc.intellij.builder.AsciiDocTargetScopeProvider: com/intellij/compiler/impl/BuildTargetScopeProvider [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:220)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:165)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:73)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:91)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:38)
	... 29 more
Caused by: java.lang.NoClassDefFoundError: com/intellij/compiler/impl/BuildTargetScopeProvider
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:335)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:330)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:294)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:217)
	... 36 more
Caused by: java.lang.ClassNotFoundException: com.intellij.compiler.impl.BuildTargetScopeProvider PluginClassLoader[org.asciidoctor.intellij.asciidoc, 0.28.25] com.intellij.ide.plugins.cl.PluginClassLoader@1fb0fac0
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 43 more
Caused by:

com.intellij.diagnostic.PluginException: While loading class org.asciidoc.intellij.builder.AsciiDocTargetScopeProvider: com/intellij/compiler/impl/BuildTargetScopeProvider [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:220)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:165)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:73)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:91)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:38)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:54)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:439)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:410)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:244)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:34)
	at com.intellij.compiler.impl.CompileDriver.mergeScopesFromProviders(CompileDriver.java:194)
	at com.intellij.compiler.impl.CompileDriver.getBuildScopes(CompileDriver.java:186)
	at com.intellij.compiler.impl.CompileDriver.compileInExternalProcess(CompileDriver.java:207)
	at com.intellij.compiler.impl.CompileDriver.lambda$isUpToDate$0(CompileDriver.java:116)
	at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressInCurrentThread(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:305)
	at com.intellij.openapi.progress.Task.queue(Task.java:115)
	at com.intellij.compiler.progress.CompilerTask.start(CompilerTask.java:414)
	at com.intellij.compiler.impl.CompileDriver.isUpToDate(CompileDriver.java:110)
	at com.intellij.compiler.CompilerManagerImpl.isUpToDate(CompilerManagerImpl.java:262)
	at com.intellij.compiler.backwardRefs.CompilerReferenceServiceBase.lambda$projectOpened$2(CompilerReferenceServiceBase.java:111)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/intellij/compiler/impl/BuildTargetScopeProvider
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:335)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:330)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:294)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:217)
	... 36 more
Caused by: java.lang.ClassNotFoundException: com.intellij.compiler.impl.BuildTargetScopeProvider PluginClassLoader[org.asciidoctor.intellij.asciidoc, 0.28.25] com.intellij.ide.plugins.cl.PluginClassLoader@1fb0fac0
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 43 more

```

AsciiDoc Plugin Version: 0.28.25

IDE Name and Version: IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019

Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8

**Comment by ahus1** [comment]
I haven't tried bundling plugins before, but can give it a try. The stack trace leads to AsciiDocTargetScopeProvider, but the class that isn't found is an IntelliJ class (BuildTargetScopeProvider).

Please name the version of the plugin plus an IntelliJ version that worked for you. This might help me to reproduce the issue. 

As a workaround while I investigate this: There is an IntelliJ configuration file [externalDependencies.xml](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/.idea/externalDependencies.xml) on a per-project basis. This will trigger a small notification to the user to install necessary plugins for the project she/he just opened. This way you might not need to bundle the plugin.

The configuration allows to specify the plugin and a minimum/maximum plugin version. The contents are managed via the IntelliJ settings menu:

![required-plugins](https://user-images.githubusercontent.com/3957921/62216375-e935b700-b3a8-11e9-91ac-d93e6a8f8716.png)

**Comment by ahus1** [comment]
I was able to reproduce it and I am developing a fix. Expect a pre-release soon.

**Comment by chwoerz** [comment]
Many thanks for your fast response. Looking forward to the release.

**Comment by ahus1** [comment]
Pre-release 0.28.26 is now available. It correctly declares the optional dependency to the Java build system. This was introduced to clear error indicators on AsciiDoc files when the user triggers "Rebuild project". This is an optional dependency, and the plugin is still usable with Non-Java IDEs.

I suggest you download this pre-release from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) or the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

I was able to reproduce the problem locally. This build fixed the problem for me. 
Please comment in this ticket if it fixes the problem for you as well.

**Comment by ahus1** [comment]
The version 0.28.26 is now generally available.
