### ISSUE TITLE
Crashing on rubymine NoClassDefFoundError StringEscapeUtils

### ISSUE THREAD

**Issue by pddzaic** [asciidoctor/asciidoctor-intellij-plugin#323]
Crashing on any adoc-file in Rubymine 2019.2.1:

Error message:

```
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringEscapeUtils
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel.lambda$setHtml$4(JavaFxHtmlPanel.java:423)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

AsciiDoc Plugin Version: 0.29.9
IDE Name and Version: Rubymine 2019.2.1

**Comment by ahus1** [comment]
I'll have a look later today - sorry that this is causing you problems. I'll look into it later today.

**Comment by ahus1** [comment]
Version 0.29.10 fixes this issue; I've been able to reproduce the problem using RubyMine locally, and was also able to reproduce that the fix resolve it. 

The new version is available from the [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and also from the JetBrains repository.
