### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by luvarqpp** [asciidoctor/asciidoctor-intellij-plugin#342]
I was editing simple text document (just headlines, lists and some bold formatting), when too many open files error popped up in preview window. It mentioned ruby script if I have seen correctly (spring restdocs thing). I was editing given document for a bit long time (hour?) with preview showing.

In console I have seen this (perhaps "post mortem" error):

```
ERROR - o.ReadWriteDirectBufferWrapper - /home/luvar/.IdeaIC2019.2/system/index/stubs/org.jetbrains.kotlin.idea.stubindex.kotlintopleveltypealiasbypackageindex/org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelTypeAliasByPackageIndex.storage (Too many open files) 
java.io.FileNotFoundException: /home/luvar/.IdeaIC2019.2/system/index/stubs/org.jetbrains.kotlin.idea.stubindex.kotlintopleveltypealiasbypackageindex/org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelTypeAliasByPackageIndex.storage (Too many open files)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at com.intellij.util.io.ReadWriteDirectBufferWrapper$FileContext$1.execute(ReadWriteDirectBufferWrapper.java:49)
	at com.intellij.util.io.ReadWriteDirectBufferWrapper$FileContext$1.execute(ReadWriteDirectBufferWrapper.java:42)
	at com.intellij.openapi.util.io.FileUtilRt.doIOOperation(FileUtilRt.java:943)
	at com.intellij.util.io.ReadWriteDirectBufferWrapper$FileContext.<init>(ReadWriteDirectBufferWrapper.java:42)
	at com.intellij.util.io.ReadWriteDirectBufferWrapper.flushWithContext(ReadWriteDirectBufferWrapper.java:85)
	at com.intellij.util.io.PagedFileStorage$StorageLock.flushBuffersForOwner(PagedFileStorage.java:736)
	at com.intellij.util.io.PagedFileStorage$StorageLock.access$600(PagedFileStorage.java:466)
	at com.intellij.util.io.PagedFileStorage.force(PagedFileStorage.java:449)
	at com.intellij.util.io.ResizeableMappedFile.force(ResizeableMappedFile.java:185)
	at com.intellij.util.io.PersistentEnumeratorBase.doFlush(PersistentEnumeratorBase.java:553)
	at com.intellij.util.io.PersistentBTreeEnumerator.doFlush(PersistentBTreeEnumerator.java:526)
	at com.intellij.util.io.PersistentEnumeratorBase.flush(PersistentEnumeratorBase.java:543)
	at com.intellij.util.io.PersistentEnumeratorBase.doClose(PersistentEnumeratorBase.java:519)
	at com.intellij.util.io.PersistentBTreeEnumerator.doClose(PersistentBTreeEnumerator.java:186)
	at com.intellij.util.io.PersistentEnumeratorBase.close(PersistentEnumeratorBase.java:506)
	at com.intellij.util.io.PersistentEnumeratorDelegate.close(PersistentEnumeratorDelegate.java:61)
	at com.intellij.util.io.PersistentHashMap.doClose(PersistentHashMap.java:751)
	at com.intellij.util.io.PersistentHashMap.close(PersistentHashMap.java:725)
	at com.intellij.util.indexing.impl.MapIndexStorage.clear(MapIndexStorage.java:182)
	at com.intellij.util.indexing.VfsAwareMapIndexStorage.clear(VfsAwareMapIndexStorage.java:145)
	at com.intellij.util.indexing.MemoryIndexStorage.clear(MemoryIndexStorage.java:129)
	at com.intellij.util.indexing.impl.MapReduceIndex.doClear(MapReduceIndex.java:153)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.doClear(VfsAwareMapReduceIndex.java:289)
	at com.intellij.util.indexing.impl.MapReduceIndex.clear(MapReduceIndex.java:142)
	at com.intellij.psi.stubs.StubIndexImpl.clearAllIndices(StubIndexImpl.java:496)
	at com.intellij.psi.stubs.StubUpdatingIndex$MyIndex.doClear(StubUpdatingIndex.java:357)
	at com.intellij.util.indexing.impl.MapReduceIndex.clear(MapReduceIndex.java:142)
	at com.intellij.util.indexing.RebuildStatus.clearIndexIfNecessary(RebuildStatus.java:44)
	at com.intellij.util.indexing.FileBasedIndexImpl.clearIndicesIfNecessary(FileBasedIndexImpl.java:1170)
	at com.intellij.util.indexing.UnindexedFilesUpdater.updateUnindexedFiles(UnindexedFilesUpdater.java:74)
	at com.intellij.util.indexing.UnindexedFilesUpdater.performInDumbMode(UnindexedFilesUpdater.java:116)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runSingleTask$9(DumbServiceImpl.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.project.DumbServiceImpl.runSingleTask(DumbServiceImpl.java:575)
	at com.intellij.openapi.project.DumbServiceImpl.runBackgroundProcess(DumbServiceImpl.java:553)
	at com.intellij.openapi.project.DumbServiceImpl.access$400(DumbServiceImpl.java:54)
	at com.intellij.openapi.project.DumbServiceImpl$4.run(DumbServiceImpl.java:510)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-10-08 15:37:50,702 [267257445]  ERROR - o.ReadWriteDirectBufferWrapper - IntelliJ IDEA 2019.2.3  Build #IC-192.6817.14 
2019-10-08 15:37:50,702 [267257445]  ERROR - o.ReadWriteDirectBufferWrapper - JDK: 11.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-10-08 15:37:50,702 [267257445]  ERROR - o.ReadWriteDirectBufferWrapper - OS: Linux 
2019-10-08 15:37:50,702 [267257445]  ERROR - o.ReadWriteDirectBufferWrapper - Last Action: Exit 
2019-10-08 15:37:50,794 [267257537]  ERROR - o.ReadWriteDirectBufferWrapper - /home/luvar/.IdeaIC2019.2/system/index/stubs/org.jetbrains.kotlin.idea.stubindex.kotlintopleveltypealiasbypackageindex/org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelTypeAliasByPackageIndex.storage (Too many open files) 
java.io.FileNotFoundException: /home/luvar/.IdeaIC2019.2/system/index/stubs/org.jetbrains.kotlin.idea.stubindex.kotl
```

AsciiDoc Plugin Version: 0.30.8

IDE Name and Version: N/A

**Comment by ahus1** [comment]
I've reviewed some open/close file operations and this will be part of the next release. 
Looking at the stack trace it doesn't show anything related to Asciidoc. Could you please run a "lsof" (list open files) or similar that shows what files are open? 

Thanks!

**Comment by luvarqpp** [comment]
Additional library folder ('project/.asciidoctor/lib') is currently opened 444 times. I have deleted it just a few minutes ago with all its content, but I see it still as opened (with deletion info). This could be former issue, or new one (deleting lib directory while idea running).
I will try to get another too many open files error in next few days, but without .asciidoctor/lib folder. Can I do something more?

**Comment by ahus1** [comment]
This gave me a hint, and I found the problem. You were right with you assumption. I will add errorprone to scan for this kind of problems automatically. 

It shouldn't affect you any more once you restart your ide as you removed the lib folder.

**Comment by luvarqpp** [comment]
Thanks. PS: This issue was/is a bit critical, because it can lead to loss of some work. Nor Idea is able to save file or its history (local history feature). I have lost about 5 minutes of writing two times (through not a big deal)...

**Comment by ahus1** [comment]
I'm sorry to hear you lost data. A new pre-release 0.30.9 is available that contains this and other changes. Please give it a try if you have the time; I'll work with it myself over the next days until I promote it to the regular release stream for all users.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by luvarqpp** [comment]
Testing is my pleasure. I have updated. Thanks.
