### ISSUE TITLE
Antora: Casting Error on all AsciiDoc Files when version is not a string

### ISSUE THREAD

**Issue by adamparker** [asciidoctor/asciidoctor-intellij-plugin#381]
AsciiDoc Plugin Version: v0.30.29

IDE Name and Version: 2018.3.1

Error rendering preview: java.lang.Double cannot be cast to java.lang.String

This happens even when there is just a simple title and nothing else.  Previewer is stuck on 'Initializing...'.

<code>
= The title of my new page
</code>

Error stacktrace from Intellij

<code>
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at org.asciidoc.intellij.AsciiDoc.mapAttribute(AsciiDoc.java:713)
	at org.asciidoc.intellij.AsciiDoc.lambda$populateAntoraAttributes$3(AsciiDoc.java:596)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:948)
	at org.asciidoc.intellij.AsciiDoc.populateAntoraAttributes(AsciiDoc.java:591)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:474)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:455)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:451)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.lambda$render$0(AsciiDocPreviewEditor.java:142)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor.lambda$execute$0(LazyApplicationPoolExecutor.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</code>

**Comment by ahus1** [comment]
Thanks for using one of the pre-releases that have initial support for Antora.

It seems that is has problems to parse the contents of an antora.yml file. 

Do you have an entry with a number value in the antora.yml file like version: 1.0" or "display-version: 1.0"?

If this is the case, please make sure to put quotes around the number values like "version: '1.0'"

This is a recommended practice to avoid converting version strings to floating point numbers that might lead to other issues as well.

Please let me know if this fixed your issue.

I'll improve parsing in the next upcoming version so that unquoted numbers will not break rendering the preview.

**Comment by adamparker** [comment]
Hi,

Yes this appears to have stopped the error.  Thanks for the hint.

Best Regards,

Adam Parker

**Comment by ahus1** [comment]
I've published a new pre-release 0.30.30 that handles missing quotes and missing values in antora.yml gracefully. I was able to reproduce the problem and the solution locally, therefore I close this issue. Please feel free to re-open it once this or a similar problem re-occurs. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
