### ISSUE TITLE
Unbalanced tree error in AsciiDoc 0.30.32

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-intellij-plugin#394]
I do get the following exception since my upgrade to 0.30.32 (probably a re-incarnation of #119):

```
Following exceptions happened soon after this one, most probably they are induced.


2020-01-27T11:54:44.539
java.lang.Throwable: Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem
language: Language: AsciiDoc, 
context: '<none>'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.lang.impl.PsiBuilderImpl.reportUnbalancedMarkers(PsiBuilderImpl.java:1112)
	at com.intellij.lang.impl.PsiBuilderImpl.assertMarkersBalanced(PsiBuilderImpl.java:1104)
	at com.intellij.lang.impl.PsiBuilderImpl.prepareLightTree(PsiBuilderImpl.java:1073)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:929)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:924)
	at org.asciidoc.intellij.parser.AsciiDocParser.parse(AsciiDocParser.java:23)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:75)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:198)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:564)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:197)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:246)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:40)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:190)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:733)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at com.intellij.psi.util.PsiFilter$Visitor.visitElement(PsiFilter.java:69)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitFile(PsiRecursiveElementVisitor.java:59)
	at org.asciidoc.intellij.psi.AsciiDocFileUtil.findSections(AsciiDocFileUtil.java:50)
	at org.asciidoc.intellij.psi.AsciiDocChooseByNameContributor.getNames(AsciiDocChooseByNameContributor.java:15)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:127)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:86)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:80)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$1(JobLauncherImpl.java:46)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:99)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)


2020-01-27T11:54:45.488
java.lang.Throwable: Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem
language: Language: AsciiDoc, 
context: '<none>'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.lang.impl.PsiBuilderImpl.reportUnbalancedMarkers(PsiBuilderImpl.java:1112)
	at com.intellij.lang.impl.PsiBuilderImpl.assertMarkersBalanced(PsiBuilderImpl.java:1104)
	at com.intellij.lang.impl.PsiBuilderImpl.prepareLightTree(PsiBuilderImpl.java:1073)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:929)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:924)
	at org.asciidoc.intellij.parser.AsciiDocParser.parse(AsciiDocParser.java:23)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:75)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:198)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:564)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:197)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:246)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:40)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:190)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:733)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at com.intellij.psi.util.PsiFilter$Visitor.visitElement(PsiFilter.java:69)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitFile(PsiRecursiveElementVisitor.java:59)
	at org.asciidoc.intellij.psi.AsciiDocFileUtil.findSections(AsciiDocFileUtil.java:50)
	at org.asciidoc.intellij.psi.AsciiDocChooseByNameContributor.getNames(AsciiDocChooseByNameContributor.java:15)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:127)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:86)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:80)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$1(JobLauncherImpl.java:46)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:99)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

```
Please provide a minimal Asciidoctor example.
Sorry, no idea where this happens and how to reproduce it on a minimal example.
But willing to install custom builds and perform regressions ;-)
```

Thanks! --> 

AsciiDoc Plugin Version: 0.30.32

IDE Name and Version: IntelliJ 2019.2.3 (Ultimate Edition)

**Comment by ahus1** [comment]
Sorry that you experience this problem. Did you recently upgrade from a previous release? This would allow me to review the changes between the previous release and the current release you use. Thanks!

**Comment by ascheman** [comment]
Switched from 0.30.31 to 0.30.32 as of today and see these errors since that time.

**Comment by ahus1** [comment]
I've looked at the code changes and didn't find a code example to reproduce it. I'd be happy if you could upgrade to the next pre-release 0.30.33 that allows extended debug and trace options: 

After you installed the release, go to "Help | Debug Log Settings..." and enter (including the hash at the beginning):

```
#org.asciidoc.intellij.parser.AsciiDocParserImpl
```

This will log additional information once an unbalanced tree is been created. It will slow down the parser a bit, but will only log information when there is a problem. 

To trace also the contents, change it to the following setting. This will log the contents on each parsing attempt. Beware: this will create a lot of logs!

```
#org.asciidoc.intellij.parser.AsciiDocParserImpl:trace
```

The logging settings can be changed at run time, no restart of the IDE is required.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by ahus1** [comment]
@ascheman provided a stack trace that lead to solving this case:

```
2020-01-28 15:24:01,856 [24640980]  ERROR - lij.lang.impl.MarkerProduction - Another not done marker added after this one. Must be done before this. 
java.lang.Throwable: Another not done marker added after this one. Must be done before this.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.lang.impl.MarkerProduction.doHeavyChecksOnMarkerDone(MarkerProduction.java:174)
	at com.intellij.lang.impl.PsiBuilderImpl.doValidityChecks(PsiBuilderImpl.java:905)
	at com.intellij.lang.impl.PsiBuilderImpl.processDone(PsiBuilderImpl.java:877)
	at com.intellij.lang.impl.PsiBuilderImpl.access$1100(PsiBuilderImpl.java:50)
	at com.intellij.lang.impl.PsiBuilderImpl$StartMarker.done(PsiBuilderImpl.java:393)
	at org.asciidoc.intellij.parser.AsciiDocParserImpl.endBlockNoDelimiter(AsciiDocParserImpl.java:514)
	at org.asciidoc.intellij.parser.AsciiDocParserImpl.lambda$parse$0(AsciiDocParserImpl.java:128)
	at com.intellij.lang.impl.PsiBuilderImpl.onSkip(PsiBuilderImpl.java:802)
	at com.intellij.lang.impl.PsiBuilderImpl.skipWhitespace(PsiBuilderImpl.java:794)
	at com.intellij.lang.impl.PsiBuilderImpl.eof(PsiBuilderImpl.java:853)
	at com.intellij.lang.impl.PsiBuilderImpl.calcTokenType(PsiBuilderImpl.java:711)
	at com.intellij.lang.impl.PsiBuilderImpl.getTokenType(PsiBuilderImpl.java:692)
	at org.asciidoc.intellij.parser.AsciiDocParserImpl.at(AsciiDocParserImpl.java:624)
	at org.asciidoc.intellij.parser.AsciiDocParserImpl.parseUrl(AsciiDocParserImpl.java:435)
	at org.asciidoc.intellij.parser.AsciiDocParserImpl.parse(AsciiDocParserImpl.java:234)
	at org.asciidoc.intellij.parser.AsciiDocParser.parse(AsciiDocParser.java:20)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.
```

I was able to synthesize a test case and fix the bug. This is part of the 0.30.34 pre-release.

Again thank you very much for running the EAP pre-releases regularly. 👏👏 This help to spot these kind of bugs before we publish releases to the regular repo. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
