### ISSUE TITLE
Plugin throwing NPE and hangs closing of IntelliJ

### ISSUE THREAD

**Issue by ctoestreich** [asciidoctor/asciidoctor-intellij-plugin#397]
```
Following exceptions happened soon after this one, most probably they are induced.


2020-02-07T08:56:41.644
java.lang.NullPointerException
	at org.asciidoc.intellij.psi.AsciiDocFileReference.resolve(AsciiDocFileReference.java:601)
	at org.asciidoc.intellij.psi.AsciiDocFileReference.resolve(AsciiDocFileReference.java:259)
	at org.asciidoc.intellij.psi.AsciiDocFileReference.multiResolve(AsciiDocFileReference.java:192)
	at org.asciidoc.intellij.psi.AsciiDocFileReference.resolve(AsciiDocFileReference.java:297)
	at org.asciidoc.intellij.quickfix.AsciiDocCreateMissingFile.isAvailable(AsciiDocCreateMissingFile.java:50)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.addAvailableFixesForGroups(ShowIntentionsPass.java:155)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getAvailableFixes$0(ShowIntentionsPass.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getAvailableFixes(ShowIntentionsPass.java:84)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:296)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:226)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

AsciiDoc Plugin Version: 0.30.31

IDE Name and Version: 

IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.39, built on January 20, 2020
Runtime version: 11.0.5+10-b520.30 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 8012M
Cores: 12
Registry: ide.editor.tabs.open.at.the.end=true, ide.tooltip.initialDelay=992
Non-Bundled Plugins: BashSupport, Lombook Plugin, Mongo Plugin, Pythonid, claims.bold.intellij.avro, com.blackbuild.intellij.maven-wrapper-support, com.dmarcotte.handlebars, com.planetexpress.go_struct_tag_generator, com.potterhsu.jsonviewer, com.wakatime.intellij.plugin, io.github.qeesung.component.HighlightBracketPair, io.protostuff.protostuff-jetbrains-plugin, mobi.hsz.idea.gitignore, org.asciidoctor.intellij.asciidoc, org.jetbrains.plugins.go-template, org.jetbrains.plugins.go

**Comment by ahus1** [comment]
Thanks for reporting this. See the code location where produces the exception but I wonder how to reproduce it locally. 

Can you provide a snippet? Did you maybe use language injection? 

Thanks!

**Comment by ahus1** [comment]
A new pre-release 0.30.37 is available that includes the fix. Please give it a try. As this is a pre-release this contains also some new features, please have a look at the [CHANGELOG](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CHANGELOG.adoc). 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
