### ISSUE TITLE
java.lang.NoClassDefFoundError when running on AdopOpenJDK

### ISSUE THREAD

**Issue by danberindei** [asciidoctor/asciidoctor-intellij-plugin#399]
I'm running IntelliJ 2020.1 EAP on jdk-13.0.1+9 from AdoptOpenJDK, which doesn't hava JavaFX.

The plugin works with the Swing preview, but this error keeps popping up:

```
java.lang.NoClassDefFoundError: com/sun/javafx/application/PlatformImpl
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanelProvider.isJavaFxStuck(JavaFxHtmlPanelProvider.java:83)
	at org.asciidoc.intellij.editor.javafx.notification.ChangeJdkForJavaFXNotificationProvider.createNotificationPanel(ChangeJdkForJavaFXNotificationProvider.java:48)
	at org.asciidoc.intellij.editor.javafx.notification.ChangeJdkForJavaFXNotificationProvider.createNotificationPanel(ChangeJdkForJavaFXNotificationProvider.java:19)
	at com.intellij.ui.EditorNotifications$Provider.createNotificationPanel(EditorNotifications.java:38)
	at com.intellij.ui.EditorNotificationsImpl.calcNotificationUpdates(EditorNotificationsImpl.java:171)
	at com.intellij.ui.EditorNotificationsImpl.lambda$updateEditors$2(EditorNotificationsImpl.java:153)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:473)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$2(NonBlockingReadActionImpl.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:977)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:162)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:600)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:546)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:149)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:438)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$0(NonBlockingReadActionImpl.java:379)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:225)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:204)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:196)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by ahus1** [comment]
A new preview release 0.30.37 is available that fixes this issue. Maybe after this change JavaFX is available for AdoptOpenJDK as well, please have a look at the settings. 

I recommend the JavaFX preview as it provides several additional features that are not available in the Swing preview (like: moving temporary images created by PlantUML to a temporary folder).

Please consider using the JDK bundled with IntelliJ as this is well-tested also with JavaFX. I've seen that other JavaFX setup were unstable and crashed. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
