### ISSUE TITLE
Cannot start the plugin with Intellij 2018.1.8

### ISSUE THREAD

**Issue by fref** [asciidoctor/asciidoctor-intellij-plugin#407]
**Situation**
On IntelliJ startup, an exception occurs during the plugin initialisation and IntelliJ subsequently disables the plugin.

**Stacktrace**
```java
Plugin 'org.asciidoctor.intellij.asciidoc' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoSuchMethodError: com.intellij.openapi.fileTypes.SyntaxHighlighterLanguageFactory.addExplicitExtension(Lcom/intellij/lang/Language;Ljava/lang/Object;)V
    at org.asciidoc.intellij.AsciiDocLanguage.<init>(AsciiDocLanguage.java:43)
    at org.asciidoc.intellij.AsciiDocLanguage.<clinit>(AsciiDocLanguage.java:34)
    at org.asciidoc.intellij.file.AsciiDocFileType.<init>(AsciiDocFileType.java:36)
    at org.asciidoc.intellij.file.AsciiDocFileType.<clinit>(AsciiDocFileType.java:31)
    at org.asciidoc.intellij.file.AsciiDocFileTypeFactory.createFileTypes(AsciiDocFileTypeFactory.java:30)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:295)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:255)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:437)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:196)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:64)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
** Environment **
AsciiDoc Plugin Version: 0.30.38
IDE Name and Version: IntelliJ IDEA 2018.1.8 (Ultimate Edition)
Build #IU-181.5684.4, built on April 3, 2019
JRE: 1.8.0_152-release-1136-b43 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ahus1** [comment]
I've missed an API incompatibility that I introduced by compiling against a newer version of IntelliJ. 

If you need to stay on 2018.1, please downgrade to version 0.30.7 of the plugin. The automatic scans indicate that it will be compatible with that version. 

If you have the chance to upgrade to 2018.3.2 you'll be able to upgrade to 0.30.34.

The latest version is only compatible with 2019.2.4 onwards.

I'll look into it to restore compatibility with earlier versions.

**Comment by fref** [comment]
I will downgrade the plugin, as for the time being, I am stuck with 2018.1 (will upgrade soon).

Thank you.

**Comment by ahus1** [comment]
I've published a backport of 0.30.34 that should work from 2017.2 onwards.
Please download asciidoctor-intellij-plugin.zip
 from https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/tag/0.30.34-2017.2 and use "Install plugin from disk..."

Please give it a try if it works for you. If it works for you, I'll publish it to the regular plugin repo.
Thanks!

**Comment by fref** [comment]
![image](https://user-images.githubusercontent.com/130824/75256165-54caf000-57e3-11ea-9405-b914d455fa6b.png)

**Comment by fref** [comment]
I'll re-try and do the update manually.

**Comment by fref** [comment]
My bad, I had a file browser opened in the plugins directory and IntelliJ couldn't make the update. This looks fine. Thank you.

**Comment by ahus1** [comment]
Thank you for your feedback. I've now officially released the backported version.

**Comment by 1250529731** [comment]
about ideal2022.2.3VERSION can't install plugin actiBpmn3.E-8
I want to install plugin actiBPM but actiBPM only fit ideal's version on 2014.xx however my ideal version is ultimate 2022.2.3 it can't install. Someone can help me how to install actiBPM on my ideal's version 2022.2.3
I want somebody can help me to solve my problem
