### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/openjfx/rt/lib/amd64/libjfxwebkit.so

### ISSUE THREAD

**Issue by Hubbitus** [asciidoctor/asciidoctor-intellij-plugin#419]
On start I see error:
```
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/openjfx/rt/lib/amd64/libjfxwebkit.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1831)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
	at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:133)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.webkit.WebPage.<clinit>(WebPage.java:132)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:881)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
	at javafx.scene.web.WebView.<init>(WebView.java:273)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel$2.lambda$run$5(JavaFxHtmlPanel.java:231)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$10(GtkApplication.java:245)
	at java.lang.Thread.run(Thread.java:748)
```

AsciiDoc Plugin Version: 0.30.41

IDE Name and Version: IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020

**Comment by ahus1** [comment]
The path in the error message looks like you're using the JDK provided by your Linux installation instead of the bundled JDK. Please consider switching to IntelliJ with the pre-bundled JDK, as this is the recommended JDK when using the AsciiDoc plugin. 

If you still want to use the pre-bundled Java version: it seems that the openjfk shipped with Linux sometimes doesn't include this library, see for example https://bugzilla.redhat.com/show_bug.cgi?id=1547378

**Comment by Hubbitus** [comment]
Yes, because that relies on ffmpeg which have patent issues to be included in "license free" distribution.

Is it strict dependency?

**Comment by Hubbitus** [comment]
And I do not want to use a bundled JDK.

**Comment by ahus1** [comment]
The JavaFX preview used WebView, an embedded browser windows. This uses an embedded webkit based browser. The name of the missing library suggests that this is then essential for the JavaFX preview.

If you want to stay with the with the given JDK, you'll need to switch to the Swing based preview. It offers fewer features. As it doesn't support CSS the same way as webkit the preview will look uglier. 

You might want to try you luck with versions available on https://openjfx.io/ -- unfortunately I don't have any first-hand experience with these versions.

There is the "open in browser" functionality that allows you to view the rendered contents in one of the systems browsers. This will give you a nice-looking preview, but no live preview (that is you'll need to refresh it manually in the browser, usually by hitting F5). 

Future versions of the plugin might use JCEF, basically a pre-bundled version of chrome. See #390 for details. Development of this feature hasn't started yet, and I am unable to give a completion date. And I don't know if you would have similar objections like for the bundled JDK. Nevertheless any help to implement this would be appreciated.

So these are the options that I see. I'm interested to hear what route you plan to take.

**Comment by ahus1** [comment]
This issue is open for about two weeks. If there are any news on this, please comment here, and I'll re-open the issue to continue the discussion.
