### ISSUE TITLE
preview doesn't render for Antora image block macro starting in 0.30.62

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#468]
I'm currently converting a Word document over to Antora/Asciidoc.  I was able to edit the following file in 0.61 in 2019.3.4, but failing in 0.64.    This is for both 2019.3.4 and 2020.1, so it doesn't seem to relate to the version of IntelliJ.

Anyway, here's the file:

https://github.com/restfulobjects/restfulobjects-spec/blob/ca111cea03d9a54088ae433975ac43068e9175e2/antora/components/spec/modules/ROOT/pages/section-a/chapter-02.adoc

Preview page shows:

unable to render AsciiDoc document
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `target' for #

org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `target' for #

(the full exception stack trace is available in the IDE's log file. Visit menu item 'Help | Show Log in Explorer' to see the log)

Full stacktrace from log:

2020-04-24 19:02:20,959 [ 236704]   WARN - org.asciidoc.intellij.AsciiDoc - unable to render AsciiDoc document 
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `target' for #<Asciidoctor::Block:0x31000f41>
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:318)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:281)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:517)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:492)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:82)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:43)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:205)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$800(ExternalToolPass.java:41)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$null$0(ExternalToolPass.java:181)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:271)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:41)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:181)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:257)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:180)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:287)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:367)
	at com.intellij.util.Alarm$Request.run(Alarm.java:357)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `target' for #<Asciidoctor::Block:0x31000f41>
	at RUBY.convert_image(<script>:19)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:65)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2580)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert_section(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:416)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:54)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2580)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.document.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert_embedded(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:318)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:62)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.document.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.convert.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:120)
2020-04-24 19:02:22,083 [ 237828]   WARN - org.asciidoc.intellij.AsciiDoc - unable to render AsciiDoc document 
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `target' for #<Asciidoctor::Block:0x32007eba>
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:318)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:281)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:517)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:492)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:488)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.lambda$render$0(AsciiDocPreviewEditor.java:143)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor.lambda$execute$0(LazyApplicationPoolExecutor.java:60)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `target' for #<Asciidoctor::Block:0x32007eba>
	at RUBY.convert_image(<script>:19)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:65)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2580)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert_section(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:416)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:54)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2580)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.document.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert_embedded(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:318)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:62)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.document.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.convert.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:120)

**Comment by ahus1** [comment]
Sorry, I broke this in the 0.30.62 pre-release. Expect an update soon. Seems that I've been trying to squeeze out the release too early.

**Comment by ahus1** [comment]
Pre-release 0.30.65 is available that fixes the problems rendering block macro images in the preview. Apparently #441 broke more elements than I expected.

I've tested the new version with the example you provided; the preview displays including the image.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
