### ISSUE TITLE
InvalidPathException

### ISSUE THREAD

**Issue by thimmy687** [asciidoctor/asciidoctor-intellij-plugin#474]
AsciiDoc Plugin Version:  0.30.59.1

IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 970M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: MatlabSupport, PlantUML integration, com.alayouni.ansiHighlight, com.github.b3er.idea.plugins.arc.browser, CheckStyle-IDEA, EclipseCodeFormatter, PDFViewer, net.scrumplex.fxmlhelper, com.intellij.ideolog, org.asciidoctor.intellij.asciidoc

Sometimes I get this exception if I play with my images and I'm not sure if it's ok that I get this message, so I want ask here.

I use a .asciidoctorconfig file with the image path.

```
java.nio.file.InvalidPathException: UNC path is missing sharename: //BigPictureSnapshot.png
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:118)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.resolve(Path.java:515)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel.findTempImageFile(JavaFxHtmlPanel.java:559)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel.prepareHtml(JavaFxHtmlPanel.java:602)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel.lambda$setHtml$4(JavaFxHtmlPanel.java:484)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

![image](https://user-images.githubusercontent.com/7715216/80480764-85e5af00-8951-11ea-9e2e-5a334d3d980e.png)

**Comment by ahus1** [comment]
Thanks for reporting this. This is a bug; I've fixed it in commit a1d3f2a42d883b3aa4714915a1a31e9359ae1092. This has been released as part of pre-release 0.30.60+. There is no official release for this, yet. 

This apparent happens when you type a path name and the path name is incomplete while you type it.

If this error message annoys you, and I you feel lucky to try a pre-release: The pre-releases of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
