### ISSUE TITLE
Issues with xref: - "invalid"

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#481]
v0.30.69

demonstrated against https://github.com/restfulobjects/restfulobjects-spec/blob/c88c2925f0b5ba0e15ab902d58707f1ca279bafe/antora/components/spec/modules/ROOT/pages/section-c/chapter-14.adoc

try tab to complete, enter to complete, down arrow.

![xref-invalid-dropdown](https://user-images.githubusercontent.com/1031625/80867460-12fb7180-8c8c-11ea-9932-a995e8587a97.gif)

**Comment by ahus1** [comment]
I've look at the video and read your comment, but I am not sure what you did, what your expectations were and what you observed. Could you please elaborate a bit more?

The "Invalid" is definitely something that shouldn't appear; but I don't know how you might have triggered it yet (some contain lists contain it, some don't, and I haven't seen it locally yet). Maybe it is an invalid index, but I thought I triggered them to be rebuilt. Hm...  

While trying out some scenarios I triggered a NPE; that's something I should definitely fix.

**Comment by ahus1** [comment]
Release 0.30.70 is available the fixes the NPE and also triggers indexes to be rebuilt. Please let me know if this fixes this problem.

**Comment by danhaywood** [comment]
Ok, will do.

**Comment by danhaywood** [comment]
Yep, seems ok now.  Thanks

**Comment by danhaywood** [comment]
hmm, still present in 0.30.70

at this commit:

https://github.com/restfulobjects/restfulobjects-spec/tree/a5056f35d56761a0cf6f8026698f74befd2fb79b

chapter-27.adoc

triggered just by typing the 3rd character.

![xref-invalid-dropdown-2](https://user-images.githubusercontent.com/1031625/80921538-ebc9a080-8d6e-11ea-9122-f7299b7c1501.gif)

**Comment by ahus1** [comment]
Hm, tried the same here, but wasn't able to reproduce it yet. 

Please have a look at the logs of the IDE: "Help | Show Log in Explorer". Anything suspicious? You can share the log with my by private email if you don't want to post it here.

An idea of last resort in case it is an indexing problem: try "File | Invalidate Caches / Restart..." (it's very brute force, and throws away all your locally created indexes, AFAIK on all projects. It will take some time to re-build the index.) 
Does the problem re-appear?

**Comment by danhaywood** [comment]
I did the invadlidate caches/restart, and the problem has indeed now gone, so maybe there was something corrupted there.

I did also look for some stack traces but I think they were for a different timestamp.  I'll copy them anyway just in case:

2020-05-03 17:29:26,001 [11552792]   WARN - org.asciidoc.intellij.AsciiDoc - unable to render AsciiDoc document 
java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.openapi.diagnostic.Logger.checkException(Logger.java:198)
	at com.intellij.idea.IdeaLogger.warn(IdeaLogger.java:82)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:529)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:493)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:83)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:43)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:205)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$800(ExternalToolPass.java:41)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$null$0(ExternalToolPass.java:181)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:271)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:41)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:181)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:257)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:180)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:287)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:367)
	at com.intellij.util.Alarm$Request.run(Alarm.java:357)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.EmptyProgressIndicator.checkCanceled(com/intellij/openapi/progress/EmptyProgressIndicator.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(com/intellij/openapi/progress/impl/CoreProgressManager.java:124)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(com/intellij/openapi/progress/ProgressManager.java:225)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(com/intellij/util/indexing/FileBasedIndexImpl.java:651)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(com/intellij/util/indexing/FileBasedIndexEx.java:211)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(com/intellij/util/indexing/FileBasedIndexEx.java:293)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(com/intellij/util/indexing/FileBasedIndexEx.java:264)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(com/intellij/util/indexing/FileBasedIndexEx.java:186)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(com/intellij/psi/search/FilenameIndex.java:186)
	at com.intellij.psi.search.FilenameIndex.processFilesByName(com/intellij/psi/search/FilenameIndex.java:85)
	at com.intellij.psi.search.FilenameIndex.processFilesByName(com/intellij/psi/search/FilenameIndex.java:72)
	at com.intellij.psi.search.FilenameIndex.getFilesByName(com/intellij/psi/search/FilenameIndex.java:140)
	at com.intellij.psi.search.FilenameIndex.getFilesByName(com/intellij/psi/search/FilenameIndex.java:63)
	at org.asciidoc.intellij.psi.AsciiDocUtil.getOtherAntoraModuleDir(org/asciidoc/intellij/psi/AsciiDocUtil.java:931)
	at org.asciidoc.intellij.psi.AsciiDocUtil.lambda$replaceAntoraPrefix$1(org/asciidoc/intellij/psi/AsciiDocUtil.java:856)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(com/intellij/openapi/application/impl/ApplicationImpl.java:884)
	at org.asciidoc.intellij.psi.AsciiDocUtil.replaceAntoraPrefix(org/asciidoc/intellij/psi/AsciiDocUtil.java:803)
	at org.asciidoc.intellij.asciidoc.AntoraReferenceAdapter.convertAntora(org/asciidoc/intellij/asciidoc/AntoraReferenceAdapter.java:107)
	at org.asciidoc.intellij.asciidoc.AntoraReferenceAdapter.convertImage(org/asciidoc/intellij/asciidoc/AntoraReferenceAdapter.java:53)
	at jdk.internal.reflect.GeneratedMethodAccessor220.invoke(jdk/internal/reflect/GeneratedMethodAccessor220)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:456)
	at org.jruby.javasupport.JavaMethod.invokeStaticDirect(org/jruby/javasupport/JavaMethod.java:368)
	at $_lt_script_gt_.invokeOther5:convertImage(<script>:19)
	at $_lt_script_gt_.convert_image(<script>:19)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.invokeOther30:convert_image(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/converter/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:65)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:65)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.invokeOther4:convert(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.invokeOther0:convert(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at org.jruby.RubyArray.collect(org/jruby/RubyArray.java:2563)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2577)
	at org.jruby.RubyArray$INVOKER$i$0$0$map19.call(org/jruby/RubyArray$INVOKER$i$0$0$map19.gen)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.invokeOther2:map(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.invokeOther41:content(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/converter/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:416)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert_section(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:416)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.invokeOther8:convert_section(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/converter/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:54)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:54)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.invokeOther4:convert(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.invokeOther0:convert(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at org.jruby.RubyArray.collect(org/jruby/RubyArray.java:2563)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2577)
	at org.jruby.RubyArray$INVOKER$i$0$0$map19.call(org/jruby/RubyArray$INVOKER$i$0$0$map19.gen)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.invokeOther2:map(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.abstract_block.RUBY$method$content$0$__VARARGS__(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.document.invokeSuper2:content(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.document.content(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.invokeOther31:content(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/converter/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:318)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert_embedded(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:318)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.invokeOther24:convert_embedded(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/converter/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:62)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.converter.html5.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:62)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.document.invokeOther39:convert(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.document.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.convert.invokeOther60:convert(uri_3a_classloader_3a_/gems/asciidoctor_minus_2_dot_0_dot_10/lib/asciidoctor/uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:120)
	at uri_3a_classloader_3a_.gems.asciidoctor_minus_2_dot_0_dot_10.lib.asciidoctor.convert.convert(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:120)
	at org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:812)
	at org.jruby.RubyBasicObject.callMethod(org/jruby/RubyBasicObject.java:376)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(org/asciidoctor/jruby/internal/JRubyAsciidoctor.java:309)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(org/asciidoctor/jruby/internal/JRubyAsciidoctor.java:281)
	at org.asciidoc.intellij.AsciiDoc.render(org/asciidoc/intellij/AsciiDoc.java:520)
	at org.asciidoc.intellij.AsciiDoc.render(org/asciidoc/intellij/AsciiDoc.java:493)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(org/asciidoc/intellij/annotator/ExternalAnnotator.java:83)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(org/asciidoc/intellij/annotator/ExternalAnnotator.java:43)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(com/intellij/codeInsight/daemon/impl/ExternalToolPass.java:205)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$800(com/intellij/codeInsight/daemon/impl/ExternalToolPass.java:41)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$null$0(com/intellij/codeInsight/daemon/impl/ExternalToolPass.java:181)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(com/intellij/codeInsight/daemon/impl/ExternalToolPass.java:271)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(com/intellij/codeInsight/daemon/impl/ExternalToolPass.java:41)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(com/intellij/codeInsight/daemon/impl/ExternalToolPass.java:181)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(com/intellij/openapi/progress/impl/CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(com/intellij/openapi/progress/impl/CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(com/intellij/openapi/progress/impl/CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(com/intellij/openapi/progress/impl/ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(com/intellij/openapi/progress/impl/CoreProgressManager.java:153)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(com/intellij/openapi/progress/util/BackgroundTaskUtil.java:257)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(com/intellij/codeInsight/daemon/impl/ExternalToolPass.java:180)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(com/intellij/util/ui/update/MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(com/intellij/util/ui/update/MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(com/intellij/util/ui/update/MergingUpdateQueue.java:273)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(com/intellij/util/ui/update/MergingUpdateQueue.java:287)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(com/intellij/util/ui/update/MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(com/intellij/util/concurrency/QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(com/intellij/util/Alarm.java:367)
	at com.intellij.util.Alarm$Request.run(com/intellij/util/Alarm.java:357)
	at java.util.concurrent.Executors$RunnableAdapter.call(java/util/concurrent/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java/util/concurrent/FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(com/intellij/util/concurrency/SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(com/intellij/util/concurrency/BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(com/intellij/util/concurrency/BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(com/intellij/util/concurrency/BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(com/intellij/util/ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(com/intellij/util/concurrency/BoundedTaskExecutor.java:190)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java/lang/Thread.java:834)
