### ISSUE TITLE
IntelliJ IDEA 2020.2 / AsciiDocPasteImageHandler has unsatisfied dependency

### ISSUE THREAD

**Issue by artspb** [asciidoctor/asciidoctor-intellij-plugin#486]
IDEA 202.2981.

```
com.intellij.diagnostic.PluginException: org.asciidoc.intellij.actions.editorAction.AsciiDocPasteImageHandler has unsatisfied dependency: interface com.intellij.openapi.editor.actionSystem.EditorTextInsertHandler among unsatisfiable dependencies: [[Ljava.lang.Class;@134600f] where DefaultPicoContainer (parent=DefaultPicoContainer (root)) was the leaf container being asked for dependencies. [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.intellij.openapi.editor.actionSystem.EditorActionHandlerBean.getHandler(EditorActionHandlerBean.java:45)
	at com.intellij.openapi.editor.actionSystem.EditorAction.getHandler(EditorAction.java:60)
	at com.intellij.openapi.editor.actions.PasteAction.update(PasteAction.java:32)
	at com.intellij.openapi.editor.actionSystem.EditorAction.updateForKeyboardAccess(EditorAction.java:127)
	at com.intellij.openapi.editor.actionSystem.EditorAction.update(EditorAction.java:160)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:290)
	at com.intellij.openapi.editor.actionSystem.EditorAction.beforeActionPerformedUpdate(EditorAction.java:142)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:189)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:630)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:608)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:505)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:459)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:217)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:889)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:834)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:816)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.picocontainer.defaults.UnsatisfiableDependenciesException: org.asciidoc.intellij.actions.editorAction.AsciiDocPasteImageHandler has unsatisfied dependency: interface com.intellij.openapi.editor.actionSystem.EditorTextInsertHandler among unsatisfiable dependencies: [[Ljava.lang.Class;@134600f] where DefaultPicoContainer (parent=DefaultPicoContainer (root)) was the leaf container being asked for dependencies.
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(CachingConstructorInjectionComponentAdapter.java:181)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:71)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:95)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:90)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiateClass(AbstractExtensionPointBean.java:86)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandlerBean.getHandler(EditorActionHandlerBean.java:40)
	... 25 more
```

**Comment by ahus1** [comment]
I read that this is version IDEA 2020.2. IMHO this is not yet EAP status, still I'll have a look at it. 
Where did you download this version?

Could you please (for completeness) paste the version information from "Help | About" (then over over the splash screen and copy the setting)?

**Comment by artspb** [comment]
It's not yet publicly available. I just wanted to let you know about possible problems when the EAP starts in about a month. I don't have more information about the version or settings as it was reported by one of the users. Sorry, I should've mentioned in the description.

**Comment by ahus1** [comment]
There is no EAP build available yet to test it. As a workaround I decided to publish a version where AsciiDocPasteImageHandler is disabled in the configuration (plugin.xml). 

This is pre-release version 0.31.1 as is intended only for those running version 2020.2 of the platform. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

In the EAP version in the EAP repository is set to require a minimum build of "202.0" (manually edited in the marketplace). Development will continue in the regular master branch for release 0.30.x; the 0.31.x branch will added functionality at a later point in time.

I'd be grateful if someone could confirm whether this workaround helps to remedy the symptoms. Thanks in advance!

**Comment by ahus1** [comment]
I was able to reproduce it in EAP 2020.2, thank for letting me know. The upcoming pre-release 0.31.2 will fix this.

**Comment by ahus1** [comment]
Pre-release 0.31.2 is now available. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
