### ISSUE TITLE
kubuntu 20.04 - NullPointerException

### ISSUE THREAD

**Issue by roganjoshua** [asciidoctor/asciidoctor-intellij-plugin#504]
```
= Introduction

Getting started.

[source, xml]
----
<elements>
<element name="attribute" />
</elements>
----
```

The rendering is not working and just says Initializing.
It should render the asiidoc.

Error rendering preview: null

java.lang.NullPointerException
	at org.asciidoc.intellij.AsciiDoc.lambda$collectAntoraAttributes$4(AsciiDoc.java:707)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.asciidoc.intellij.AsciiDoc.lambda$collectAntoraAttributes$5(AsciiDoc.java:707)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:869)
	at org.asciidoc.intellij.AsciiDoc.collectAntoraAttributes(AsciiDoc.java:692)
	at org.asciidoc.intellij.AsciiDoc.populateAntoraAttributes(AsciiDoc.java:652)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:502)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:489)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:485)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.lambda$render$0(AsciiDocPreviewEditor.java:144)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor.lambda$execute$0(LazyApplicationPoolExecutor.java:60)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

AsciiDoc Plugin Version: 0.30.73

IDE Name and Version: _____
![image](https://user-images.githubusercontent.com/2682346/83672258-e1006680-a5cd-11ea-8bfb-06da330f529f.png)

I changed to rbenv from rvm - not sure that is the issue?

**Comment by roganjoshua** [comment]
By the way, I would just like to say how enjoyable using your plugin is, for aciidoc and antora

**Comment by ahus1** [comment]
Thanks for using this plugin. I'm sorry you see this error message. 

I traced the issue down to the "asciidoc" section of an antora.yml file. I assume you've set an attribute to maybe null or nothing? 

Please post a small example as a comment to this ticket.

As a workaround you can set for example an empty string like below: 

```
# excerpt from an antora.yml file
asciidoc:
  attributes:
    # removing the quotes below allowed me to reproduce the exception you saw
    prodname: ""
 ```

Depending on the example you send, the next version of the plugin will most likely assume an empty string if no string is set.

**Comment by roganjoshua** [comment]
You are absolutely correct

**Comment by roganjoshua** [comment]
also 
unable to render AsciiDoc document
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NameError: (NameError) asciidoctor: FAILED: /home/marty/development/documentation/learning/modules/Asciidoctor/pages/index.adoc: Failed to load AsciiDoc document - uninitialized constant Rouge::Lexers

org.jruby.exceptions.NameError: (NameError) asciidoctor: FAILED: /home/marty/development/documentation/learning/modules/Asciidoctor/pages/index.adoc: Failed to load AsciiDoc document - uninitialized constant Rouge::Lexers

(the full exception stack trace is available in the IDE's log file. Visit menu item 'Help | Show Log in Explorer' to see the log)

**Comment by roganjoshua** [comment]
asciidoc: 
  attributes: 
    experimental:
    unsafe:

**Comment by ahus1** [comment]
I've gave Antora a short test run. Antora will treat in your example the `experimental:` as unset.

If you want to make it explicitly unset, use `experimental: false`. If you want to make it set, use `experimental: ''`

These both work with the current version of the plugin.

The next version of the plugin will have a better validation and error message.

**Comment by ahus1** [comment]
The improved handling of Antora attributes in part of the 0.30.78 release.
