### ISSUE TITLE
NoClassDefFoundError on CLion 

### ISSUE THREAD

**Issue by flaviodesousa** [asciidoctor/asciidoctor-intellij-plugin#51]
When the AsciiDoc plugin is enabled I get a NoClassDefFoundError notification whenever I right click over an editor window (even non-asciidoc files) or project window.

The AsciiDoc rightclick menu option is shown, but empty ("Nothing here" message)

Plugin version: 0.7
CLion CL-140.1221.2
JRE 1.7.0_65-b32amd64

=== Details

update failed for AnAction with ID=asciidoc.maketitle: com/intellij/openapi/actionSystem/DataKeys
java.lang.NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys
	at org.asciidoc.intellij.actions.asciidoc.AsciiDocAction.update(AsciiDocAction.java:26)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:113)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:193)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:141)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:285)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.g(ActionMenu.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$400(ActionMenu.java:41)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:235)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1043)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1122)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
	at javax.swing.JMenu.setSelected(JMenu.java:311)
	at javax.swing.JMenu.menuSelectionChanged(JMenu.java:1190)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.menuSelectionChanged(ActionMenu.java:209)
	at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:117)
	at javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(BasicMenuUI.java:511)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3311)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4620)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4474)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:572)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:383)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by harrol** [comment]
DataKeys is deprecated and probably has been removed in the newer version of the IDEA platform.

(I hate it when code gets deprecated without comments describing what to use instead)

**Comment by aheusingfeld** [comment]
@harrol in general I couldn't agree more. In our specific case, I'd assume that they wanted to align with the other distributions and we are supposed to use [PlatformDataKeys](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/openapi/actionSystem/PlatformDataKeys.java) instead (See this bug report in their forum: https://devnet.jetbrains.com/message/5502403?tstart=0).
Unfortunately I couldn't find the sources for the `DataKeys` class to compare it - maybe that part of "openapi" is only present in IntelliJ itself?

**Comment by harrol** [comment]
Thanks for finding that issue; makes things a lot easier :) I downloaded PyCharm CE and can reproduce the error. I'll see if the suggestions from the issue solve it.
