### ISSUE TITLE
Non AsciiDoc Plugin Exception reported as an AsciiDoc Plugin Exception by IntelliJ IDEA

### ISSUE THREAD

**Issue by Javaru** [asciidoctor/asciidoctor-intellij-plugin#523]
This is more of a heads up... IntelliJ IDEA reported an exception in the AsciiDoc Plugin. But the first line of the exception showed a class from the [Markdown Navigator Plugin](https://github.com/vsch/idea-multimarkdown).  (See screenshot below.) I opened [an issue ](https://github.com/vsch/idea-multimarkdown/issues/870)with that plugin for the exception. But I thought you might want a heads up on it. Not sure why IntelliJ IDEA saw it as an exception in your plugin. Not sure if there is some sort of conflict with the registering of the Markdown Navigator plugin and AsciiDoc Plugin? To the best of my knowledge, Markdown Navigator does not support AsciiDoc files. And I do not see AsciiDoc listed on its [feature matrix](https://vladsch.com/product/markdown-navigator).

AsciiDoc Plugin Version: 0.31.14

IDE Name and Version:
IntelliJ IDEA 2020.2 Beta (Ultimate Edition)
Build #IU-202.6397.20, built on July 15, 2020
IntelliJ IDEA EAP User
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 7 6.1
GC: ParNew, ConcurrentMarkSweep
Memory: 16275M
Cores: 16

```
com.intellij.diagnostic.PluginException: execute() delegated to original paste handler, Cannot convert the following Java element class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl due to `unexpected symbol class org.jetbrains.kotlin.nj2k.symbols.JKMultiverseMethodSymbol` [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.vladsch.md.nav.enh.actions.handlers.MdPasteHandler.doExecute(MdPasteHandler.java:366)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:52)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:89)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:98)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:73)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:610)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:471)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:220)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:888)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:833)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments: Cannot convert the following Java element class com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl due to `unexpected symbol class org.jetbrains.kotlin.nj2k.symbols.JKMultiverseMethodSymbol`
	at org.jetbrains.kotlin.nj2k.JavaToJKTreeBuilder.throwCanNotConvertError(JavaToJKTreeBuilder.kt:1034)
	at org.jetbrains.kotlin.nj2k.JavaToJKTreeBuilder.access$throwCanNotConvertError(JavaToJKTreeBuilder.kt:56)
	at org.jetbrains.kotlin.nj2k.JavaToJKTreeBuilder$ExpressionTreeMapper.toJK(JavaToJKTreeBuilder.kt:470)
	at org.jetbrains.kotlin.nj2k.JavaToJKTreeBuilder$ExpressionTreeMapper.toJK(JavaToJKTreeBuilder.kt:164)
	at org.jetbrains.kotlin.nj2k.JavaToJKTreeBuilder.buildTree(JavaToJKTreeBuilder.kt:1015)
	at org.jetbrains.kotlin.nj2k.NewJavaToKotlinConverter.elementsToKotlin(NewJavaToKotlinConverter.kt:145)
	at org.jetbrains.kotlin.nj2k.NewJavaToKotlinConverter.elementsToKotlin(NewJavaToKotlinConverter.kt:195)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1$1.invoke(ConvertJavaCopyPasteProcessor.kt:272)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1$1.invoke(ConvertJavaCopyPasteProcessor.kt)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt$sam$com_intellij_openapi_util_Computable$0.compute(ApplicationUtils.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:855)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runReadAction(ApplicationUtils.kt:28)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1.compute(ConvertJavaCopyPasteProcessor.kt:272)
	at org.jetbrains.kotlin.idea.conversion.copy.ConvertJavaCopyPasteProcessorKt$convertCodeToKotlin$1.compute(ConvertJavaCopyPasteProcessor.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

![image](https://user-images.githubusercontent.com/2196944/87878091-17dce100-c9b0-11ea-99b9-33d586ebe12e.png)

**Comment by ahus1** [comment]
Thanks for reporting this here. The background to why IDEA blaims the AsciiDoc plugin might be as follows: 

A plugin can register for the "EditorPaste" editor action. The first thing a plugin will do is to find out if it wants to handle the call. If it decides not to handle the call, it forwards it to the original handler. This leads to a caller chain. The AsciiDoc plugin will only handle cases when an image is pasted to an AsciiDoc file.

In the situation described in the stack trace the problem occurred when when pasting Java code to a Kotlin file (?) somewhere in ConvertJavaCopyPasteProcessorKt - I assume neither the Markdown nor the AsciiDoc plugin would be interested. The message "execute() delegated to original paste handler" from the Markdown plugin seems to support that. 

I tried to look up the code of the Markdown plugin but didn't find MdPasteHandler.java in the master branch. I wonder if it catches/wrapps the existing exception. I decided not to do this in this plugin's paste handler (AsciiDocPasteImageHandler).
 
I started watching the issue you linked above. As there is nothing more to do for this ticket as of now, I'll close this issue. 

Thanks for the heads up. Once something to change in this plugin's coding arises, comment here and I'll re-open the ticket.
