### ISSUE TITLE
IllegalArgumentException in AsciiDocPasteImageHandler

### ISSUE THREAD

**Issue by ewirch** [asciidoctor/asciidoctor-intellij-plugin#605]
## Observed vs. expected behavior

IntelliJ recorded an exception:

```
java.lang.IllegalArgumentException: Invalid range specified: (-1, 0); 
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:222)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:217)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:213)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:41)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:30)
	at com.intellij.openapi.util.TextRange.shiftLeft(TextRange.java:133)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.correctRangeByInjection(PsiBasedFormattingModel.java:137)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWithPSI(PsiBasedFormattingModel.java:99)
	at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWhiteSpace(PsiBasedFormattingModel.java:67)
	at com.intellij.formatting.engine.FormatProcessorUtils.replaceWhiteSpace(FormatProcessorUtils.java:31)
	at com.intellij.formatting.engine.ApplyChangesState.doIteration(ApplyChangesState.java:175)
	at com.intellij.formatting.engine.State.iteration(State.java:25)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:26)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:108)
	at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:705)
	at com.intellij.formatting.FormatterImpl.execute(FormatterImpl.java:274)
	at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:239)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processRange(CodeFormatterFacade.java:97)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatRangeImpl(CodeStyleManagerImpl.java:316)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatRange(CodeStyleManagerImpl.java:142)
	at com.intellij.codeInsight.editorActions.PasteHandler.reformatBlock(PasteHandler.java:315)
	at com.intellij.codeInsight.editorActions.PasteHandler.lambda$doPaste$4(PasteHandler.java:240)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1000)
	at com.intellij.codeInsight.editorActions.PasteHandler.doPaste(PasteHandler.java:221)
	at com.intellij.codeInsight.editorActions.PasteHandler.lambda$execute$2(PasteHandler.java:111)
	at com.intellij.openapi.project.DumbService.runWithAlternativeResolveEnabled(DumbService.java:367)
	at com.intellij.codeInsight.editorActions.PasteHandler.execute(PasteHandler.java:102)
	at org.asciidoc.intellij.actions.editorAction.AsciiDocPasteImageHandler.execute(AsciiDocPasteImageHandler.java:71)
	at org.asciidoc.intellij.actions.editorAction.AsciiDocPasteImageHandler.doExecute(AsciiDocPasteImageHandler.java:44)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:52)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:89)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:98)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:73)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:615)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:675)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:674)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:522)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:892)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## Steps to reproduce

I occurred when I was pasting a big chunk of XML code in to  a text block:
```
        //language=xml
        var reservationXml = """
            <-- paste here -->
         """;
```

## Environment

Plugin Version: 0.32.2

IntelliJ Details: IntelliJ IDEA 2020.3 RC (Ultimate Edition)
Build #IU-203.5981.114, built on November 26, 2020
Licensed to Eduard Wirch
Subscription is active until January 28, 2021
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.9.3-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 1126M
Cores: 8
Registry: diff.patience.alg=true, debugger.valueTooltipAutoShow=false, ide.usages.page.size=200, show.diff.as.editor.tab=true, external.system.auto.import.disabled=true, debugger.watches.in.variables=false, unknown.sdk=false
Non-Bundled Plugins: com.ivanovych666.intellij.plugin.jsonsorter, org.intellij.plugins.hcl, name.kropp.intellij.makefile, org.nik.presentation-assistant, GrepConsole, org.asciidoctor.intellij.asciidoc, Pythonid
Current Desktop: Undefined

**Comment by ahus1** [comment]
Hi Edward, I'm sorry to hear your IDE presented you with this exception. 

The AsciiDoc plugin appears in the stack trace of this exception, but actually didn't do anything here but delegate the call to the original handler. It would only invoke its own logic when a user pastes an image from the clipboard to an AsciiDoc file. Therefore I ask you to report this exception to JetBrains. 

I'll use this opportunity to find out how I could keep this plugin out of the exception stacktrace to prevent it to either interfere or to be accused to be the cause.

**Comment by ahus1** [comment]
The next upcoming release will no longer implement this extension point as pasting of files from the clipboard seems to work without implementing it in the latest IntelliJ release.

**Comment by ahus1** [comment]
Pre-release 0.32.5 is now available.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
