### ISSUE TITLE
NullPointerException when opening asciidoc file in the light editor

### ISSUE THREAD

**Issue by rocketraman** [asciidoctor/asciidoctor-intellij-plugin#606]
## Observed vs. expected behavior

Crash when attempting to open an adoc file with light edit mode with IDEA 2020.3 (i.e. `idea -e foo.adoc`)

```
java.lang.NullPointerException
	at org.asciidoc.intellij.psi.AsciiDocUtil.findSpringRestDocSnippets(AsciiDocUtil.java:759)
	at org.asciidoc.intellij.psi.AsciiDocUtil.findSpringRestDocSnippets(AsciiDocUtil.java:777)
	at org.asciidoc.intellij.editor.notification.SpringBootRestDocsNotificationProvider.createNotificationPanel(SpringBootRestDocsNotificationProvider.java:70)
	at org.asciidoc.intellij.editor.notification.SpringBootRestDocsNotificationProvider.createNotificationPanel(SpringBootRestDocsNotificationProvider.java:30)
	at com.intellij.ui.EditorNotificationsImpl.calcNotificationUpdates(EditorNotificationsImpl.java:170)
	at com.intellij.ui.EditorNotificationsImpl.lambda$updateEditors$2(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## Steps to reproduce

With IDEA 2020.3 open a file in light edit mode:

```
idea -e foo.adoc
```

## Environment

Plugin Version: 0.32.2

IntelliJ Details: 

```
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on November 30, 2020
Runtime version: 11.0.9+11-b944.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.9.8-100.fc32.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 3959M
Cores: 32
Non-Bundled Plugins: AceJump, Key Promoter X, claims.bold.intellij.avro, com.jetbrains.ChooseRuntime, com.karateca.jasmineDescriber, com.khmelyuk.multirun, io.protostuff.protostuff-jetbrains-plugin, app.teamhub, com.intellij.kubernetes, VisualVMLauncher, at.knittl.intellij.plugins.jmhack, google-search, org.jetbrains.jumpToLine, com.jetbrains.codeWithMe, org.jetbrains.kotlin, zielu.gittoolbox, com.google.gct.core, org.intellij.scala, com.intellij.lang.jsgraphql, Pythonid, ru.adelf.idea.dotenv, org.asciidoctor.intellij.asciidoc
Current Desktop: KDE
```

**Comment by ahus1** [comment]
Thank you for reporting this. I have to admit that the light edit mode is not well supported yet. I'll fix this exception in the next upcoming release.

**Comment by ahus1** [comment]
I found several places that threw exceptions when in light editing mode. This is due the fact that no indexes are available in light edit mode, therefore some of the auto-complete will not work. 

I'll update the ticket once a pre-release is available. I'm afraid light editing mode will need some more testing event with that upcoming pre-release.

**Comment by ahus1** [comment]
Pre-release 0.32.3 is now available that fixes the exception you reported. 

If you discover more incompatibilities with the light mode, it should be enough to create a new issue with one or more stack traces plus environment. You can keep the "steps to reproduce" minimal and just name it "editing in light mode". 

If you would come up with more than 5 different exceptions, please be so kind and pause submitting new exceptions until I publish a new pre-release.

Happy light mode editing!

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by rocketraman** [comment]
> Pre-release 0.32.3 is now available that fixes the exception you reported.

I tried this version on several files, some of them quite complex. I opened the file, and made some edits while the preview was open. I used some ToC links, clicked on the asciidoc render to see the editor scroll to the correct position, and vice-versa.

Didn't run into any further issues!
