### ISSUE TITLE
"Invalid root file" error message after deleting a file or a parent folder

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#676]
Reported by Sentry as ASCIIDOC-INTELLIJ-PLUGIN-1C

```
java.lang.Throwable: Invalid root *** (invalid) in com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.SourceFolderBridge@c81aecbb
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
    at com.intellij.openapi.roots.impl.RootFileSupplier.ensureValid(RootFileSupplier.java:114)
    at com.intellij.openapi.roots.impl.RootIndex.ensureValid(RootIndex.java:317)
    at com.intellij.openapi.roots.impl.RootIndex.buildRootInfo(RootIndex.java:185)
    at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:72)
    at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:171)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:154)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:181)
    at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:98)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:27)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:140)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:135)
    at org.asciidoc.intellij.psi.AsciiDocUtil$1.after(AsciiDocUtil.java:614)
    at jdk.internal.reflect.GeneratedMethodAccessor151.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by ahus1** [comment]
The root file should only be determined for files that are still valid (that is: have not been deleted or have their parents deleted). Fixed in next upcoming release.
