### ISSUE TITLE
IllegalStateException @NotNull method org/asciidoc/intellij/psi/AsciiDocUtil.collectBlockId must not return null

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#677]
Reported by Sentry: [ASCIIDOC-INTELLIJ-PLUGIN-1J](https://sentry.io/organizations/alexander-schwartz/issues/2226532803)

Plugin version: 0.32.19

```
java.lang.IllegalStateException: @NotNull method org/asciidoc/intellij/psi/AsciiDocUtil.collectBlockId must not return null
    at org.asciidoc.intellij.psi.AsciiDocUtil.$$$reportNull$$$0(AsciiDocUtil.java)
    at org.asciidoc.intellij.psi.AsciiDocUtil.collectBlockId(AsciiDocUtil.java:120)
    at org.asciidoc.intellij.psi.AsciiDocUtil.findIds(AsciiDocUtil.java:97)
    at org.asciidoc.intellij.psi.AsciiDocChooseByNameContributor.getItemsByName(AsciiDocChooseByNameContributor.java:47)
    at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.lambda$getElementsByName$4(ContributorsBasedGotoByModel.java:198)
    at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$0(JobLauncherImpl.java:50)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
    at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$1(JobLauncherImpl.java:50)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
    at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
    at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by ahus1** [comment]
Will be fixed in upcoming release.
