### ISSUE TITLE
AlreadyDisposedException in logs related to caching of module roots

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#683]
Reported via Sentry.

Plugin Version: 0.32.20
IntelliJ Details: IU 2020.3.2

```
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: '****' (disposed)
    at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:167)
    at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:409)
    at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java:37)
    at com.intellij.openapi.roots.impl.RootIndex.buildRootInfo(RootIndex.java:159)
    at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:72)
    at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:171)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:154)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:181)
    at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:98)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:27)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:140)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:135)
    at org.asciidoc.intellij.psi.AsciiDocUtil$1.after(AsciiDocUtil.java:580)
    at jdk.internal.reflect.GeneratedMethodAccessor151.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:652)
    at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:426)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:401)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:383)
    at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
    at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:182)
```

**Comment by ahus1** [comment]
Similar: 

```
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: '***' (disposed)
    at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:167)
    at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:409)
    at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java:37)
    at com.intellij.openapi.roots.impl.RootIndex.buildRootInfo(RootIndex.java:159)
    at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:72)
    at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:171)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:154)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:181)
    at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:98)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:27)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isUnderIgnored(ProjectFileIndexImpl.java:87)
    at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.isUnderIgnored(ProjectFileIndexFacade.java:62)
    at com.intellij.psi.impl.file.impl.FileManagerImpl.isExcludedOrIgnored(FileManagerImpl.java:431)
    at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:417)
    at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:409)
    at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:167)
    at com.intellij.psi.AbstractFileViewProvider.shouldCreatePsi(AbstractFileViewProvider.java:92)
    at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:145)
    at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:99)
    at com.intellij.psi.AbstractFileViewProvider.getPsi(AbstractFileViewProvider.java:196)
    at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:369)
    at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:154)
    at com.intellij.ide.impl.dataRules.PsiFileRule.getData(PsiFileRule.java:38)
    at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:97)
    at com.intellij.ide.impl.DataManagerImpl.getData(DataManagerImpl.java:71)
    at com.intellij.ide.impl.DataManagerImpl$MyDataContext.calcData(DataManagerImpl.java:370)
    at com.intellij.ide.impl.DataManagerImpl$MyDataContext.doGetData(DataManagerImpl.java:362)
    at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:341)
    at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:40)
    at com.intellij.openapi.actionSystem.AnActionEvent.getData(AnActionEvent.java:184)
    at org.asciidoc.intellij.actions.asciidoc.AsciiDocAction.update(AsciiDocAction.java:23)
```

**Comment by ahus1** [comment]
Will be fixed in upcoming release.
