### ISSUE TITLE
Whitespace element contains non-whitespace-characters: '{ '

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#685]
Reported by Sentry:  ASCIIDOC-INTELLIJ-PLUGIN-1S

```
java.lang.IllegalStateException: Whitespace element contains non-whitespace-characters: '{ ' at offset ***
    at org.asciidoc.intellij.formatting.AsciiDocBlock.buildChildren(AsciiDocBlock.java:85)
    at com.intellij.psi.formatter.common.AbstractBlock.getSubBlocks(AbstractBlock.java:47)
    at com.intellij.psi.formatter.common.NewLineBlocksIterator.pushAll(NewLineBlocksIterator.java:135)
    at com.intellij.psi.formatter.common.NewLineBlocksIterator.popUntilTopBlockStartOffsetGreaterOrEqual(NewLineBlocksIterator.java:120)
    at com.intellij.psi.formatter.common.NewLineBlocksIterator.popUntilTopBlockStartsNewLine(NewLineBlocksIterator.java:67)
```

Plugin Version: 0.32.17
IntelliJ Details: IC 2020.3.2

**Comment by ahus1** [comment]
Again a missing return in the lexer, so the "{" would become part of the next token. Fixed in next release.
