### ISSUE TITLE
Cannot find file by /jsonSchemas/antoraComponentSchema.json

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#687]
Reported by Sentry

Plugin Version: 0.32.17-20 and later
IntelliJ Details: IU 2020.3.2

``` 
java.lang.Throwable: Cannot find file by /jsonSchemas/antoraComponentSchema.json
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
    at com.jetbrains.jsonSchema.extension.JsonSchemaProviderFactory.getResourceFile(JsonSchemaProviderFactory.java:38)
    at org.asciidoc.intellij.antora.AsciiDocAntoraSchemaProviderFactory$AntoraComponentSchemaFileProvider.lambda$new$0(AsciiDocAntoraSchemaProviderFactory.java:27)
    at com.intellij.openapi.util.NullableLazyValue$1.compute(NullableLazyValue.java:52)
    at com.intellij.openapi.util.NullableLazyValue.getValue(NullableLazyValue.java:36)
    at org.asciidoc.intellij.antora.AsciiDocAntoraSchemaProviderFactory$AntoraComponentSchemaFileProvider.getSchemaFile(AsciiDocAntoraSchemaProviderFactory.java:44)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getSchemaForProvider(JsonSchemaServiceImpl.java:600)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState.createFileProviderMap(JsonSchemaServiceImpl.java:574)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.compute(JsonSchemaServiceImpl.java:507)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.compute(JsonSchemaServiceImpl.java:503)
    at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:39)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.getValue(JsonSchemaServiceImpl.java:515)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.getValue(JsonSchemaServiceImpl.java:503)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getProvidersForFile(JsonSchemaServiceImpl.java:235)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getSchemasForFile(JsonSchemaServiceImpl.java:179)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getSchemaFilesForFile(JsonSchemaServiceImpl.java:163)
    at org.jetbrains.plugins.github.extensions.GithubYamlIconProvider.getIcon(GithubYamlIconProvider.kt:24)
    at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
    at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:87)
    at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:83)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
    at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:83)
    at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:43)
    at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:282)
    at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:169)
    at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:101)
    at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:169)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:97)
    at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$5(DeferredIconImpl.java:168)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:834)

```

**Comment by ahus1** [comment]
Opened issue in YouTrack: https://youtrack.jetbrains.com/issue/IDEA-262831

Will experiment to load the JSON Schema via VirtualFileManager#refreshAndFindFileByUrl() if it is not available.

**Comment by ahus1** [comment]
Yann Cebron suggested: 

> please try to remove caching via NullableLazyValue.createValue in your ctors and return VirtualFile from com.jetbrains.jsonSchema.extension.JsonSchemaFileProvider#getSchemaFile implementations without any caching and tricks

I took this "trick" for caching from JsonSchemaProjectSelfProviderFactory, but will remove it and will roll out an update. It might take a week or two to find out if this resolves the issue as I am unable to reproduce the problem locally.

**Comment by ahus1** [comment]
Published release 0.32.22, see if this still occurs.

**Comment by ahus1** [comment]
Issue still occurs, as reported via Sentry. Next step: think of a workaround, new issue in YouTrack

```
java.lang.Throwable: Cannot find file by /jsonSchemas/antoraComponentSchema.json
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
    at com.jetbrains.jsonSchema.extension.JsonSchemaProviderFactory.getResourceFile(JsonSchemaProviderFactory.java:38)
    at org.asciidoc.intellij.antora.AsciiDocAntoraSchemaProviderFactory$AntoraComponentSchemaFileProvider.getSchemaFile(AsciiDocAntoraSchemaProviderFactory.java:37)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getSchemaForProvider(JsonSchemaServiceImpl.java:600)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState.createFileProviderMap(JsonSchemaServiceImpl.java:574)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.compute(JsonSchemaServiceImpl.java:507)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.compute(JsonSchemaServiceImpl.java:503)
    at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:39)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.getValue(JsonSchemaServiceImpl.java:515)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl$MyState$1.getValue(JsonSchemaServiceImpl.java:503)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getProvidersForFile(JsonSchemaServiceImpl.java:235)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getSchemasForFile(JsonSchemaServiceImpl.java:179)
    at com.jetbrains.jsonSchema.impl.JsonSchemaServiceImpl.getSchemaFilesForFile(JsonSchemaServiceImpl.java:163)
    at org.jetbrains.plugins.github.extensions.GithubYamlIconProvider.getIcon(GithubYamlIconProvider.kt:24)
    at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
    at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
    at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:221)
    at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:154)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$updateFileIconAsynchronously$5(EditorsSplitters.java:400)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
    at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by ahus1** [comment]
New issue reported at JetBrains: https://youtrack.jetbrains.com/issue/IDEA-262981

The workaround to read the JSON schema by resource seems to hold; no new exceptions reports by Sentry. Closing this issue.
