### ISSUE TITLE
Logged recursion problem when analyzing tags

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#723]
The following was reported by Sentry for plugin version 0.32.36 on IU 2021.1, possibly when trying to multi-resolve an include tag.

<details><summary>java.lang.Throwable: recursion at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)</summary>
<p>
``` 
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionMembersCache.getSyntheticModifiers(GrTypeDefinitionMembersCache.java:104)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionImpl.getSyntheticModifiers(GrTypeDefinitionImpl.java:697)
    at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrModifierListUtil.hasSyntheticModifier(modifiers.kt:69)
    at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrModifierListUtil.hasModifierProperty(modifiers.kt:51)
    at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrModifierListUtil.hasModifierProperty$default(modifiers.kt:48)
    at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrModifierListUtil.hasModifierProperty(modifiers.kt)
    at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrModifierListImpl.hasModifierProperty(GrModifierListImpl.java:155)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionImpl.hasModifierProperty(GrTypeDefinitionImpl.java:488)
    at com.intellij.psi.util.PsiUtil.typeParametersIterable(PsiUtil.java:957)
    at com.intellij.psi.util.PsiUtil.captureToplevelWildcards(PsiUtil.java:835)
    at com.intellij.psi.util.PsiUtil.equalOnEquivalentClasses(PsiUtil.java:671)
    at com.intellij.psi.PsiClassType.equals(PsiClassType.java:105)
    at java.util.Objects.equals(Objects.java:77)
    at java.util.ArrayList.equalsArrayList(ArrayList.java:593)
    at java.util.ArrayList.equals(ArrayList.java:561)
    at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
    at org.jetbrains.plugins.groovy.transformations.TransformationContextImpl$AST_TRANSFORMATION_AWARE_METHOD_PARAMETERS_ERASURE_EQUALITY$1.equals(TransformationContextImpl.kt:301)
    at org.jetbrains.plugins.groovy.transformations.TransformationContextImpl$AST_TRANSFORMATION_AWARE_METHOD_PARAMETERS_ERASURE_EQUALITY$1.equals(TransformationContextImpl.kt:66)
    at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.add(ObjectOpenCustomHashSet.java:313)
    at org.jetbrains.plugins.groovy.transformations.TransformationContextImpl.doAddMethod(TransformationContextImpl.kt:213)
    at org.jetbrains.plugins.groovy.transformations.TransformationContextImpl.addMethod(TransformationContextImpl.kt:225)
    at org.jetbrains.plugins.groovy.transformations.TransformationContext.addMethod(TransformationContext.java:92)
    at org.jetbrains.plugins.groovy.transformations.TransformationContextImpl.addMethods(TransformationContextImpl.kt:237)
    at org.jetbrains.plugins.groovy.transformations.impl.TraitTransformationSupport.lambda$applyTransformation$0(TraitTransformationSupport.java:41)
    at org.jetbrains.plugins.groovy.transformations.impl.TraitTransformationSupport.process(TraitTransformationSupport.java:77)
    at org.jetbrains.plugins.groovy.transformations.impl.TraitTransformationSupport.applyTransformation(TraitTransformationSupport.java:36)
    at org.jetbrains.plugins.groovy.transformations.TransformationUtilKt$transformDefinition$1.compute(TransformationUtil.kt:53)
    at org.jetbrains.plugins.groovy.transformations.TransformationUtilKt$transformDefinition$1.compute(TransformationUtil.kt)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at org.jetbrains.plugins.groovy.transformations.TransformationUtilKt.transformDefinition(TransformationUtil.kt:49)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionMembersCache.lambda$getTransformationResult$10(GrTypeDefinitionMembersCache.java:114)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionMembersCache.getTransformationResult(GrTypeDefinitionMembersCache.java:113)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionMembersCache.lambda$getExtendsListTypes$5(GrTypeDefinitionMembersCache.java:85)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionMembersCache.getExtendsListTypes(GrTypeDefinitionMembersCache.java:84)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionImpl.getExtendsListTypes(GrTypeDefinitionImpl.java:222)
    at org.jetbrains.plugins.groovy.lang.psi.api.statements.typedef.GrTypeDefinition.getExtendsListTypes(GrTypeDefinition.java:49)
    at com.intellij.psi.impl.ScopedClassHierarchy.getSuperTypes(ScopedClassHierarchy.java:83)
    at com.intellij.psi.impl.ScopedClassHierarchy.visitType(ScopedClassHierarchy.java:68)
    at com.intellij.psi.impl.ScopedClassHierarchy.getSuperClassSubstitutor(ScopedClassHierarchy.java:106)
    at com.intellij.psi.impl.JavaClassSupersImpl.getSuperSubstitutorWithCaching(JavaClassSupersImpl.java:95)
    at com.intellij.psi.impl.JavaClassSupersImpl.getSuperClassSubstitutor(JavaClassSupersImpl.java:55)
    at com.intellij.psi.impl.InheritanceImplUtil.isInheritor(InheritanceImplUtil.java:27)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionImpl.isInheritor(GrTypeDefinitionImpl.java:422)
    at com.intellij.psi.util.InheritanceUtil.isInheritorOrSelf(InheritanceUtil.java:29)
    at com.intellij.psi.util.InheritanceUtil.isInheritor(InheritanceUtil.java:85)
    at com.intellij.psi.util.InheritanceUtil.isInheritor(InheritanceUtil.java:71)
    at com.intellij.psi.util.InheritanceUtil.isInheritor(InheritanceUtil.java:57)
    at org.jetbrains.plugins.groovy.lang.resolve.ReceiverKt.processMapType(receiver.kt:82)
    at org.jetbrains.plugins.groovy.lang.resolve.ReceiverKt.processClassType(receiver.kt:68)
    at org.jetbrains.plugins.groovy.lang.resolve.ReceiverKt.doProcessReceiverType(receiver.kt:50)
    at org.jetbrains.plugins.groovy.lang.resolve.ReceiverKt.doProcessReceiverType0(receiver.kt:31)
    at org.jetbrains.plugins.groovy.lang.resolve.ReceiverKt.processReceiverType(receiver.kt:27)
    at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.processAllDeclarations(ResolveUtil.java:237)
    at org.jetbrains.plugins.groovy.lang.psi.impl.FunctionalExpressionsKt.processDelegate(functionalExpressions.kt:86)
    at org.jetbrains.plugins.groovy.lang.psi.impl.FunctionalExpressionsKt.processDelegatesTo(functionalExpressions.kt:71)
    at org.jetbrains.plugins.groovy.lang.psi.impl.FunctionalExpressionsKt.processOwnerAndDelegate(functionalExpressions.kt:51)
    at org.jetbrains.plugins.groovy.lang.psi.impl.FunctionalExpressionsKt.processDeclarationsWithCallsite(functionalExpressions.kt:61)
    at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.doProcessDeclarations(ResolveUtil.java:123)
    at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.lambda$treeWalkUp$0(ResolveUtil.java:108)
    at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1229)
    at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtil.treeWalkUp(ResolveUtil.java:106)
    at org.jetbrains.plugins.groovy.lang.resolve.ResolveUtilKt.treeWalkUp(ResolveUtil.kt:41)
    at org.jetbrains.plugins.groovy.lang.resolve.GrReferenceResolveRunner.resolveReferenceExpression(GrReferenceResolveRunner.kt:37)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionReference.doResolveNonStatic(GrReferenceExpressionReference.kt:40)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionReference.doResolve(GrReferenceExpressionReference.kt:32)
    at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference$DefaultResolver.resolve(GroovyCachingReference.kt:21)
    at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference$DefaultResolver.resolve(GroovyCachingReference.kt:19)
    at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
    at com.intellij.openapi.util.Computable.get(Computable.java:17)
    at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:237)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
    at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.resolveWithCaching(TopInferenceContext.kt:23)
    at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext.resolve(InferenceContext.java:47)
    at org.jetbrains.plugins.groovy.lang.resolve.api.GroovyCachingReference.resolve(GroovyCachingReference.kt:16)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl$1.doResolve(GrReferenceExpressionImpl.java:525)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl$1.doResolve(GrReferenceExpressionImpl.java:467)
    at org.jetbrains.plugins.groovy.lang.resolve.DependentResolver.resolve(DependentResolver.kt:27)
    at org.jetbrains.plugins.groovy.lang.resolve.DependentResolver.resolve(DependentResolver.kt:10)
    at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
    at com.intellij.openapi.util.Computable.get(Computable.java:17)
    at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:237)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
    at org.jetbrains.plugins.groovy.lang.psi.impl.TopInferenceContext.resolveWithCaching(TopInferenceContext.kt:23)
    at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext.resolve(InferenceContext.java:47)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.resolve(GrReferenceExpressionImpl.java:560)
    at org.jetbrains.plugins.groovy.lang.psi.api.GroovyReference.advancedResolve(GroovyReference.java:29)
    at org.jetbrains.plugins.groovy.lang.psi.api.GroovyReference.resolve(GroovyReference.java:24)
    at org.intellij.plugins.intelliLang.inject.groovy.GrConcatenationInjector.findLanguageParams(GrConcatenationInjector.java:73)
    at org.intellij.plugins.intelliLang.inject.groovy.GrConcatenationInjector.processInPlace(GrConcatenationInjector.java:60)
    at org.intellij.plugins.intelliLang.inject.groovy.GrConcatenationInjector.getLanguagesToInject(GrConcatenationInjector.java:56)
    at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:441)
    at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUp(InjectedLanguageUtilBase.java:247)
    at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.enumerate(InjectedLanguageUtilBase.java:177)
    at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:331)
    at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.doGetReferencesByElement(InjectedReferencesContributor.java:101)
    at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.lambda$getInjectionInfo$0(InjectedReferencesContributor.java:62)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
    at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor.getInjectionInfo(InjectedReferencesContributor.java:60)
    at org.intellij.plugins.intelliLang.references.InjectedReferencesContributor$1.getReferencesByElement(InjectedReferencesContributor.java:54)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:201)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:164)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:143)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
    at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
    at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.literals.GrLiteralImpl.getReferences(GrLiteralImpl.java:156)
    at org.asciidoc.intellij.psi.AsciiDocIncludeTagReferenceInComment.lambda$multiResolve$0(AsciiDocIncludeTagReferenceInComment.java:34)
    at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:937)
    at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
    at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:67)
    at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:24)
    at com.intellij.util.WalkingState.walkChildren(WalkingState.java:62)
    at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
    at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:76)
    at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
    at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:938)
    at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
    at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
    at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:934)
    at org.asciidoc.intellij.psi.AsciiDocIncludeTagReferenceInComment.multiResolve(AsciiDocIncludeTagReferenceInComment.java:33)
    at org.asciidoc.intellij.psi.AsciiDocIncludeTagReferenceInComment.resolve(AsciiDocIncludeTagReferenceInComment.java:52)
    at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitElement(RefManagerImpl.java:473)
    at com.intellij.psi.PsiElementVisitor.visitComment(PsiElementVisitor.java:59)
    at com.intellij.psi.impl.source.tree.PsiCommentImpl.accept(PsiCommentImpl.java:38)
    at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitElement(RefManagerImpl.java:509)
    at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.accept(LazyParseablePsiElement.java:242)
    at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitElement(RefManagerImpl.java:509)
    at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
    at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitElement(RefManagerImpl.java:509)
    at com.intellij.codeInspection.reference.RefManagerImpl$ProjectIterator.visitFile(RefManagerImpl.java:524)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
    at com.intellij.analysis.AnalysisScope.doProcessFile(AnalysisScope.java:428)
    at com.intellij.analysis.AnalysisScope.lambda$processFile$7(AnalysisScope.java:375)
    at com.intellij.analysis.AnalysisScope.lambda$commitAndRunInSmartMode$8(AnalysisScope.java:391)
    at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$7(PsiDocumentManagerBase.java:518)
    at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$8(PsiDocumentManagerBase.java:543)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
    at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
    at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:541)
    at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:518)
    at com.intellij.analysis.AnalysisScope.commitAndRunInSmartMode(AnalysisScope.java:389)
    at com.intellij.analysis.AnalysisScope.processFile(AnalysisScope.java:375)
    at com.intellij.analysis.AnalysisScope.lambda$acceptImpl$0(AnalysisScope.java:282)
    at com.intellij.analysis.AnalysisScope.lambda$createScopeIterator$5(AnalysisScope.java:356)
    at com.intellij.openapi.roots.impl.FileIndexBase.lambda$toContentIteratorEx$0(FileIndexBase.java:78)
    at com.intellij.openapi.roots.impl.FileIndexBase$1.visitFileEx(FileIndexBase.java:60)
    at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:293)
    at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
    at com.intellij.openapi.roots.impl.FileIndexBase.iterateContentUnderDirectory(FileIndexBase.java:41)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContentUnderDirectory(ProjectFileIndexImpl.java:27)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:43)
    at com.intellij.openapi.roots.impl.FileIndexBase.iterateContent(FileIndexBase.java:33)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:27)
    at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:334)
    at com.intellij.analysis.AnalysisScope.acceptImpl(AnalysisScope.java:277)
    at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:261)
    at com.intellij.codeInspection.reference.RefManagerImpl.findAllDeclarations(RefManagerImpl.java:336)
    at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$runGlobalTools$15(GlobalInspectionContextImpl.java:585)
    at com.intellij.codeInspection.ex.InspectionEventsKt.reportWhenActivityFinished(inspectionEvents.kt:18)
    at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runGlobalTools(GlobalInspectionContextImpl.java:581)
    at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:269)
    at com.intellij.codeInspection.ex.GlobalInspectionContextBase.lambda$performInspectionsWithProgress$4(GlobalInspectionContextBase.java:261)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:261)
    at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:214)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:834)
```
</p>
</details>

**Comment by ahus1** [comment]
Will be fixed in upcoming release.

**Comment by ahus1** [comment]
This is part of pre-release 0.32.37. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
