### ISSUE TITLE
Stub index points to a file without indexed stub tree / but file should have been indexed

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#725]
The following error was reported by Sentry for plugin version 0.32.36 / IU 2021.1

Users might experience problems that features with auto-complete and validation not work as expected.

**UPDATE 2021-04-22:** Preview-Build for 2021.1.1 is available here that includes a fix. They are available from the JetBrains Toolbox and via https://confluence.jetbrains.com/display/IDEADEV/IDEA+2021.1+latest+builds

<details><summary>java.lang.Throwable: Stub index points to a file</summary>
<p>

```
java.lang.Throwable: Stub index points to a file (file = file:///***.adoc, file type = org.asciidoc.intellij.file.AsciiDocFileType@1b75c9c3, indexed file type = org.asciidoc.intellij.file.AsciiDocFileType@1b75c9c3) without indexed stub tree; indexing stamp = indexing timestamp = 1618298071538, binary = false, byte size = 513, char size = 527, can have stubs = true
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
    at com.intellij.psi.stubs.StubProcessingHelper.retrieveStubIdList(StubProcessingHelper.java:42)
    at com.intellij.psi.stubs.StubIndexImpl.lambda$processElements$4(StubIndexImpl.java:323)
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:322)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:92)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:80)
    at org.asciidoc.intellij.psi.AsciiDocAttributeDeclarationKeyIndex.get(AsciiDocAttributeDeclarationKeyIndex.java:49)
    at org.asciidoc.intellij.psi.AsciiDocUtil.findAttributes(AsciiDocUtil.java:270)
    at org.asciidoc.intellij.psi.AsciiDocUtil.findAttributes(AsciiDocUtil.java:370)
    at org.asciidoc.intellij.psi.AsciiDocUtil.resolveAttributes(AsciiDocUtil.java:1032)
    at org.asciidoc.intellij.psi.AsciiDocBlockMacro.getResolvedBody(AsciiDocBlockMacro.java:193)
    at org.asciidoc.intellij.inspections.AsciiDocLinkResolveInspection$1.visitElement(AsciiDocLinkResolveInspection.java:75)
    at org.asciidoc.intellij.inspections.AsciiDocVisitor.visitBlocks(AsciiDocVisitor.java:15)
    at org.asciidoc.intellij.psi.AsciiDocStandardBlock.accept(AsciiDocStandardBlock.java:26)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
    at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:56)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:320)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:279)
    at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:161)
    at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:153)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:277)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:277)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
    at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
    at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
    at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
    at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

</p>
</details>

**Comment by YannCebron** [comment]
Please try builds from https://youtrack.jetbrains.com/issue/IDEA-266391 to see if bug still reproduces

**Comment by ahus1** [comment]
Preview-Build for 2021.1.1 is available here that includes a fix. https://confluence.jetbrains.com/display/IDEADEV/IDEA+2021.1+latest+builds 

Users can also install it via the JetBrains Toolbox.

**Comment by ahus1** [comment]
Next plugin version will ask users to update to 2021.1.1 preview version and will link to this issue.

**Comment by ahus1** [comment]
IntelliJ Release 2021.1.1 is available here that includes the fix.
