### ISSUE TITLE
MyRefreshPreviewListener / already disposed

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#729]
The following exception was reported via Sentry in IU 2021.1 / plugin 0.32.36:

```
java.lang.Throwable: Assertion failed: Already disposed
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:197)
    at com.intellij.util.Alarm.checkDisposed(Alarm.java:66)
    at com.intellij.util.Alarm._addRequest(Alarm.java:195)
    at com.intellij.util.Alarm.addRequest(Alarm.java:178)
    at org.asciidoc.intellij.editor.AsciiDocPreviewEditor$MyRefreshPreviewListener.refreshPreview(AsciiDocPreviewEditor.java:258)
    at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:674)
    at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:649)
    at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:422)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:397)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:379)
    at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
    at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:185)
    at com.sun.proxy.$Proxy270.refreshPreview
    at org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel.disposeMyself(AsciiDocJCEFHtmlPanel.java:722)
    at org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel.setHtml(AsciiDocJCEFHtmlPanel.java:618)
    at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.lambda$render$0(AsciiDocPreviewEditor.java:175)
    at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor.lambda$execute$0(LazyApplicationPoolExecutor.java:55)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by ahus1** [comment]
Fixed in upcoming release.
