### ISSUE TITLE
Error: Injection AsciiDocListing contradicts literalTextEscaper

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#732]
Via Sentry, the following error was reported: 

> Injection host of class org.asciidoc.intellij.psi.AsciiDocListing with range (8114,8179) contains injection at (8114,8114), which contradicts literalTextEscaper that only allows injection at (8143,8175) [Plugin: org.asciidoctor.intellij.asciidoc]

<details>
<summary>stacktrace</summary>

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Injection host of class org.asciidoc.intellij.psi.AsciiDocListing with range (8114,8179) contains injection at (8114,8114), which contradicts literalTextEscaper that only allows injection at (8143,8175)
    at com.intellij.codeInsight.completion.CompletionInitializationUtil.checkInjectionConsistency(CompletionInitializationUtil.java:244)
    at com.intellij.codeInsight.completion.CompletionInitializationUtil.setOriginalFile(CompletionInitializationUtil.java:211)
    at com.intellij.codeInsight.completion.CompletionInitializationUtil.toInjectedIfAny(CompletionInitializationUtil.java:185)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:346)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
    at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:345)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:834)
com.intellij.diagnostic.PluginException: Injection host of class org.asciidoc.intellij.psi.AsciiDocListing with range (8114,8179) contains injection at (8114,8114), which contradicts literalTextEscaper that only allows injection at (8143,8175) [Plugin: org.asciidoctor.intellij.asciidoc]
    at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:300)
    at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
    at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
    at com.intellij.codeInsight.completion.CompletionInitializationUtil.checkInjectionConsistency(CompletionInitializationUtil.java:244)
    at com.intellij.codeInsight.completion.CompletionInitializationUtil.setOriginalFile(CompletionInitializationUtil.java:211)
    at com.intellij.codeInsight.completion.CompletionInitializationUtil.toInjectedIfAny(CompletionInitializationUtil.java:185)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:346)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
    at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
    at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:345)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:834)
```

</details>

IDE: IC 2021.1
Plugin: 0.32.37

Active plugin | version
-- | --
AsciiDoc | 0.32.37
gradle-intellij-plugin wizard | 1.4.1
Kotlin | 211-1.4.32-release-IJ6693.72

**Comment by ahus1** [comment]
Unfortunately, the user didn't add the attachment or provided a sample document.

**Comment by ahus1** [comment]
I search my code and found that I returned an empty range where I wanted to prevent automatic language injection based on the content. Although I didn't manage to reproduce it, I assume this interacted badly with an already open fragment editor once a user entered content that triggered it. No issue on the intellij side IMHO.

Change will be included in upcoming release.
