### ISSUE TITLE
Assertion failed: Directory index can only be queried after project initialization

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#733]
Problem reported by Sentry for IU 2021.1 / 0.32.37

```
java.lang.Throwable: Assertion failed: Directory index can only be queried after project initialization
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:197)
    at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:69)
    at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:171)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:154)
    at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:181)
    at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:98)
    at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.getInfoForFileOrDirectory(ModuleFileIndexImpl.java:20)
    at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.lambda$getModuleRootsToIterate$0(ModuleFileIndexImpl.java:52)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:844)
    at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
    at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.getModuleRootsToIterate(ModuleFileIndexImpl.java:43)
    at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.iterateContent(ModuleFileIndexImpl.java:33)
    at com.intellij.openapi.roots.impl.FileIndexBase.iterateContent(FileIndexBase.java:33)
    at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.iterateContent(ModuleFileIndexImpl.java:20)
    at org.asciidoc.intellij.builder.AsciiDocTargetScopeProvider.clearProblemsForAsciidocFiles(AsciiDocTargetScopeProvider.java:35)
    at org.asciidoc.intellij.builder.AsciiDocTargetScopeProvider.getBuildTargetScopes(AsciiDocTargetScopeProvider.java:28)
    at com.intellij.compiler.impl.CompileDriver.lambda$mergeScopesFromProviders$1(CompileDriver.java:215)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
    at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
    at com.intellij.compiler.impl.CompileDriver.mergeScopesFromProviders(CompileDriver.java:213)
    at com.intellij.compiler.impl.CompileDriver.getBuildScopes(CompileDriver.java:204)
    at com.intellij.compiler.impl.CompileDriver.compileInExternalProcess(CompileDriver.java:225)
    at com.intellij.compiler.impl.CompileDriver.lambda$isUpToDate$0(CompileDriver.java:122)
    at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:161)
    at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:272)
    at com.intellij.compiler.impl.CompileDriver.isUpToDate(CompileDriver.java:148)
    at com.intellij.compiler.CompilerManagerImpl.isUpToDate(CompilerManagerImpl.java:329)
    at com.intellij.compiler.backwardRefs.CompilerReferenceServiceBase.<init>(CompilerReferenceServiceBase.java:111)
    at com.intellij.compiler.backwardRefs.CompilerReferenceServiceImpl.<init>(CompilerReferenceServiceImpl.java:35)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
    at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:771)
    at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:49)
    at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:13)
    at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.run(ServiceComponentAdapter.kt:43)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
    at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:42)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
    at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:488)
    at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
    at com.intellij.compiler.CompilerReferenceService.getInstanceIfEnabled(CompilerReferenceService.java:28)
    at com.intellij.compiler.backwardRefs.CompilerReferenceServiceImpl$InitializationActivity.runActivity(CompilerReferenceServiceImpl.java:296)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
    at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$4(StartupManagerImpl.java:235)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:303)
    at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:156)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:229)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
    at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$projectOpened$1(StartupManagerImpl.java:160)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by ahus1** [comment]
fixed in upcoming release.
