### ISSUE TITLE
URLDecoder: Incomplete trailing escape (%) pattern

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#736]
Reported by Sentry / plugin version 0.32.37

```
java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
    at java.net.URLDecoder.decode(URLDecoder.java:225)
    at java.net.URLDecoder.decode(URLDecoder.java:142)
    at org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel.prepareHtml(AsciiDocJCEFHtmlPanel.java:768)
    at org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel.setHtml(AsciiDocJCEFHtmlPanel.java:639)
    at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.lambda$render$0(AsciiDocPreviewEditor.java:175)
    at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor.lambda$execute$0(LazyApplicationPoolExecutor.java:55)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by ahus1** [comment]
When entering a URL, the preview tries to decode the URL-encoded parts (with percentage signs). If the URL was entered by a user, it might be incomplete. Ignore decoding problems.

Will be fixed in upcoming release.
