### ISSUE TITLE
StringIndexOutOfBoundsException / when formatting via toolbar

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#739]
Reported by Sentry for plugin version 0.32.37: 

```
java.lang.StringIndexOutOfBoundsException: begin 2, end 1, length 3
    at java.lang.String.checkBoundsBeginEnd(String.java:3319)
    at java.lang.String.substring(String.java:1874)
    at org.asciidoc.intellij.actions.asciidoc.SimpleFormatAsciiDocAction.removeSymbol(SimpleFormatAsciiDocAction.java:56)
    at org.asciidoc.intellij.actions.asciidoc.SimpleFormatAsciiDocAction.removeSymbol(SimpleFormatAsciiDocAction.java:47)
    at org.asciidoc.intellij.actions.asciidoc.SimpleFormatAsciiDocAction.updateSelectionIntern(SimpleFormatAsciiDocAction.java:32)
    at org.asciidoc.intellij.actions.asciidoc.SimpleFormatAsciiDocAction.updateSelection(SimpleFormatAsciiDocAction.java:27)
    at org.asciidoc.intellij.actions.asciidoc.FormatAsciiDocAction.actionPerformed(FormatAsciiDocAction.java:49)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
    at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
    at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
    at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
    at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:201)
    at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:174)
    at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:157)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:470)
    at java.awt.Component.processEvent(Component.java:6417)
    at java.awt.Container.processEvent(Container.java:2263)
    at java.awt.Component.dispatchEventImpl(Component.java:5027)
    at java.awt.Container.dispatchEventImpl(Container.java:2321)
    at java.awt.Component.dispatchEvent(Component.java:4859)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
    at java.awt.Container.dispatchEventImpl(Container.java:2307)
    at java.awt.Window.dispatchEventImpl(Window.java:2780)
    at java.awt.Component.dispatchEvent(Component.java:4859)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
    at java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
    at java.awt.EventQueue$5.run(EventQueue.java:751)
    at java.awt.EventQueue$5.run(EventQueue.java:749)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
    at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ahus1** [comment]
Will be fixed in upcoming release.
