### ISSUE TITLE
IntelliJ 2021.1 / 2021.1.1 freezes when loading arbitrary .adoc files after rendering timeout

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-intellij-plugin#765]
**UPDATE 2021-05-28 by @ahus1:** Upgrade to IDEA 2021.1.2 RC should fix this. Download it from https://confluence.jetbrains.com/display/IDEADEV/IDEA+2021.1+latest+builds

## Observed vs. expected behavior

IntelliJ aborts when loading arbitrary .adoc files, even very small ones with only a few lines.
It works for some time and then just stops working when loading another existing .adoc file.

A restart of IntelliJ is required when the problem occurs.

## Steps to reproduce

Just work with IntelliJ and after some time it aborts when loading a file.

In the log I always see errors like this:

```
2021-05-26 12:55:38,558 [14645068]  DEBUG - BackendServerFileEditorManager - Opening host editor for .../xxx.adoc
2021-05-26 12:55:38,571 [14645081]   INFO - ntellij.analysis.SonarLintTask - SonarLint analysis done
2021-05-26 12:55:41,547 [14648057]   WARN - tor.jcef.AsciiDocJCEFHtmlPanel - rendering didn't complete in time, might be slow or broken
2021-05-26 12:55:41,547 [14648057]   WARN - tor.jcef.AsciiDocJCEFHtmlPanel - triggering disposal of preview
```

## Environment

IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Licensed to Gerd Aschemann
Subscription is active until January 10, 2022.
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
Jenkins Plugin 0.13.11-2020.3
GC: G1 Young Generation, G1 Old Generation
Memory: 6120M
Cores: 16
Registry: ide.balloon.shadow.size=0, ide.images.show.chessboard=true
Non-Bundled Plugins: CMD Support (1.0.5), Key Promoter X (2021.1.1), SnakeYAML plugin (1.17.0), claims.bold.intellij.avro (0.3.1), codes.rudolph.idea.cfg (0.3.1), com.alayouni.ansiHighlight (1.2.4), com.andrewbrookins.wrap_to_column (1.4.0), com.github.b3er.idea.plugins.arc.browser (0.23), com.intellij.apacheConfig (211.6693.108), com.intellij.ideolog (203.0.27.0), com.jetbrains.ChooseRuntime (1.2), com.jetbrains.plugins.ini4idea (211.6693.44), com.webschik.doT (1.5.4), net.seesharpsoft.intellij.plugins.csv (2.16.3), net.vektah.codeglance (1.5.4), org.intellij.plugins.hcl (0.7.10), org.jetbrains.plugins.go-template (211.6693.44), com.codestream.jetbrains-codestream (11.0.7+147), com.github.novotnyr.gitlab-quickmr-idea-plugin (21), mobi.hsz.idea.gitignore (4.1.0), name.kropp.intellij.makefile (211.6693.108), org.jetbrains.plugins.vagrant (211.6693.111), AWSCloudFormation (211.6693.108), com.intellij.lang.puppet (211.6693.44), com.theodo.serverless.plugin.serverless-plugin (1.3.0), ir.msdehghan.plugins.ansible (0.92), ru.sadv1r.ansible-vault-editor-idea-plugin (1.13), org.logtalk (1.0.15), org.mayevskiy.intellij.sonar (2.9.9), CheckStyle-IDEA (5.52.0), CopyRestUrl (1.5), com.intellij.kubernetes (211.7142.13), Error-prone plugin (211.7142.13), GrepConsole (11.9.211.6086.0), Groovy Console Plugin (0.1.5), Jenkins Control Plugin (0.13.11-2020.3), de.docksnet.puml.syntaxchecker (0.2.0), de.kontext_e.idea.plugins.jqa (2.0), io.thundra.debugger (1.3), org.sonarlint.idea (4.16.0.31683), com.neueda4j.intellij.plugin.cypher (3.0.3), com.perl5 (2021.1), com.jetbrains.plugins.jade (211.6693.65), Dart (211.7233), org.jetbrains.plugins.vue (211.7142.13), org.jetbrains.kotlin (211-1.5.10-release-891-IJ7142.45), org.mapstruct.intellij (1.2.4), Osmorc (211.6693.65), org.intellij.scala (2021.1.20), com.jetbrains.php (211.7142.45), com.intellij.phing (211.6693.44), org.jetbrains.plugins.ruby (211.7142.36), PlantUML integration (5.3.0), Pythonid (211.7142.45), com.intellij.selenium (211.7036.8), org.asciidoctor.intellij.asciidoc (0.32.48), org.jetbrains.plugins.go (211.7142.36), ru.adelf.idea.dotenv (2021.1)
Kotlin: 211-1.5.10-release-891-IJ7142.45

**Comment by ahus1** [comment]
Thanks for providing stack traces via a private channel. 

Looking at the stack traces, I didn't find any classes of the AsciiDoc plugin involved. One thread was BLOCKED and waiting on another thread. Both have AWT in their name, and blocked AWT threads match your error description about the IDE to be frozen. 

There is an upstream issue here: https://youtrack.jetbrains.com/issue/JBR-3460

Do you run an accessibility tool that might cause the same effect as described in the upstream issue? 

They were using Talon. Sometimes a tool might use the accessibility APIs to do something different.

```
"AWT-AppKit" #18 daemon prio=5 os_prio=31 cpu=22817.94ms elapsed=4231.81s tid=0x00007ffe15a43000 nid=0x307 waiting for monitor entry  [0x00007ffeed2e0000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.awt.Component.getAccessibleStateSet(java.desktop@11.0.10/Component.java:9976)
	- waiting to lock <0x0000000683dcfb50> (a java.awt.Component$AWTTreeLock)
	at java.awt.Component$AccessibleAWTComponent.getAccessibleStateSet(java.desktop@11.0.10/Component.java:9527)
	at javax.swing.JComponent$AccessibleJComponent.getAccessibleStateSet(java.desktop@11.0.10/JComponent.java:3932)
	at javax.swing.JTree$AccessibleJTree$AccessibleJTreeNode.getAccessibleStateSet(java.desktop@11.0.10/JTree.java:4848)
	at sun.lwawt.macosx.CAccessibility.getChildrenAndRolesRecursive(java.desktop@11.0.10/CAccessibility.java:660)
	at sun.lwawt.macosx.CAccessibility.getChildrenAndRolesRecursive(java.desktop@11.0.10/CAccessibility.java:668)
	at sun.lwawt.macosx.CAccessibility.getChildrenAndRolesRecursive(java.desktop@11.0.10/CAccessibility.java:668)
	at sun.lwawt.macosx.CAccessibility.getChildrenAndRolesRecursive(java.desktop@11.0.10/CAccessibility.java:668)

"AWT-EventQueue-0" #28 prio=6 os_prio=31 cpu=69294.65ms elapsed=4231.49s tid=0x00007ffda283a800 nid=0xe503 waiting on condition  [0x00007000088a0000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x00000006eb42e560> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.10/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.10/AbstractQueuedSynchronizer.java:2081)
	at java.util.concurrent.LinkedBlockingQueue.take(java.base@11.0.10/LinkedBlockingQueue.java:433)
	at sun.awt.AWTThreading.execute(java.desktop@11.0.10/AWTThreading.java:147)
	at sun.awt.AWTThreading.executeWaitToolkit(java.desktop@11.0.10/AWTThreading.java:80)
	at sun.awt.AWTThreading.executeWaitToolkit(java.desktop@11.0.10/AWTThreading.java:53)
	at sun.lwawt.macosx.CPlatformWindow.createNSWindow(java.desktop@11.0.10/CPlatformWindow.java:1424)
	at sun.lwawt.macosx.CPlatformWindow.lambda$initialize$1(java.desktop@11.0.10/CPlatformWindow.java:381)
	at sun.lwawt.macosx.CPlatformWindow$$Lambda$2813/0x0000000801faec40.run(java.desktop@11.0.10/Unknown Source)
	at sun.lwawt.macosx.CFRetainedResource.executeGet(java.desktop@11.0.10/CFRetainedResource.java:157)
	at sun.lwawt.macosx.CPlatformWindow.lambda$initialize$2(java.desktop@11.0.10/CPlatformWindow.java:375)
	at sun.lwawt.macosx.CPlatformWindow$$Lambda$261/0x0000000800305040.run(java.desktop@11.0.10/Unknown Source)
	at sun.lwawt.macosx.CFRetainedResource.execute(java.desktop@11.0.10/CFRetainedResource.java:134)
	at sun.lwawt.macosx.CPlatformWindow.initialize(java.desktop@11.0.10/CPlatformWindow.java:371)
	at sun.lwawt.LWWindowPeer.<init>(java.desktop@11.0.10/LWWindowPeer.java:191)
	at sun.lwawt.LWToolkit.createDelegatedPeer(java.desktop@11.0.10/LWToolkit.java:212)
	at sun.lwawt.LWToolkit.createWindow(java.desktop@11.0.10/LWToolkit.java:234)
	at java.awt.Window.addNotify(java.desktop@11.0.10/Window.java:782)
	- locked <0x0000000683dcfb50> (a java.awt.Component$AWTTreeLock)
	at java.awt.Window.show(java.desktop@11.0.10/Window.java:1049)
	at java.awt.Component.show(java.desktop@11.0.10/Component.java:1732)
	at java.awt.Component.setVisible(java.desktop@11.0.10/Component.java:1679)
	at java.awt.Window.setVisible(java.desktop@11.0.10/Window.java:1032)
	at com.intellij.ui.popup.MovablePopup.setVisible(MovablePopup.java:198)
	at com.intellij.ui.AbstractExpandableItemsHandler.doHandleSelectionChange(AbstractExpandableItemsHandler.java:267)
	at com.intellij.ui.AbstractExpandableItemsHandler.lambda$handleSelectionChange$0(AbstractExpandableItemsHandler.java:238)
	at com.intellij.ui.AbstractExpandableItemsHandler$$Lambda$5871/0x00000008034ca040.run(Unknown Source)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.10/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11.0.10/FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$446/0x0000000800543040.run(Unknown Source)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.10/InvocationEvent.java:313)
	at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.10/EventQueue.java:776)
	at java.awt.EventQueue$4.run(java.desktop@11.0.10/EventQueue.java:727)
	at java.awt.EventQueue$4.run(java.desktop@11.0.10/EventQueue.java:721)
	at java.security.AccessController.doPrivileged(java.base@11.0.10/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.10/ProtectionDomain.java:85)
	at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.10/EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.ide.IdeEventQueue$$Lambda$627/0x000000080074a440.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.ide.IdeEventQueue$$Lambda$626/0x000000080074bc40.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.10/EventDispatchThread.java:203)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.10/EventDispatchThread.java:124)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.10/EventDispatchThread.java:113)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.10/EventDispatchThread.java:109)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.10/EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.run(java.desktop@11.0.10/EventDispatchThread.java:90)

```

**Comment by ahus1** [comment]
The upstream issue I mentioned about is linked to https://youtrack.jetbrains.com/issue/IDEA-266474. 
That issue mentioned that this is fixed in "2021.1.2 Preview". 
It includes an additional list of accessibility tools that might interfere, like CatchMouse and Vimac .

In the meantime, version IDEA 2021.1.2 RC has been published that is even more recent.

Do you want to give that new version a try? I usually download the preview versions via the JetBrains Toolbox. 
You can also download the latest version here: https://confluence.jetbrains.com/display/IDEADEV/IDEA+2021.1+latest+builds

**Comment by ahus1** [comment]
Feedback from Gerd as of yesterday: upgraded to IDEA 2021.1.2 RC and 0.32.49. So far no freezes.

**Comment by ascheman** [comment]
From my point of view the problem seems to be solved with the update. Will re-open/comment when I run into the problem again.

**Comment by ahus1** [comment]
Version 0.32.50 is now available that asks users to upgrade when running on macOS and IntelliJ 2021.1 + 2021.1.1
