### ISSUE TITLE
ClassCastException in connection class loader problems

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#859]
## Observed vs. expected behavior

Sometimes there is a exception

> java.lang.ClassCastException: class org.asciidoc.intellij.psi.AsciiDocBlockMacro cannot be cast to class com.intellij.psi.PsiNamedElement (org.asciidoc.intellij.psi.AsciiDocBlockMacro is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @298b94b0; com.intellij.psi.PsiNamedElement is in unnamed module of loader com.intellij.util.lang.PathClassLoader @531be3c5)

or 

> java.lang.LinkageError: loader constraint violation: loader 'app' wants to load abstract class com.intellij.openapi.diagnostic.Logger. A different abstract class with the same name was previously loaded by com.intellij.util.lang.PathClassLoader @f5f2bb7. (com.intellij.openapi.diagnostic.Logger is in unnamed module of loader com.intellij.util.lang.PathClassLoader @f5f2bb7)

## Steps to reproduce

Not able to reproduce, some reports via Sentry

## Environment

First observed with IntelliJ 2021.2 EAP releases. Occurs on Windows, Mac and Linux.

**Comment by ahus1** [comment]
Example

```
java.lang.ClassCastException: class org.asciidoc.intellij.psi.AsciiDocBlockMacro cannot be cast to class com.intellij.psi.PsiNamedElement (org.asciidoc.intellij.psi.AsciiDocBlockMacro is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @298b94b0; com.intellij.psi.PsiNamedElement is in unnamed module of loader com.intellij.util.lang.PathClassLoader @531be3c5)
    at org.asciidoc.intellij.findUsages.AsciiDocFindUsagesProvider.getDescriptiveName(AsciiDocFindUsagesProvider.java:43)
    at com.intellij.lang.findUsages.LanguageFindUsages.lambda$getDescriptiveName$1(LanguageFindUsages.java:64)
    at com.intellij.lang.findUsages.LanguageFindUsages.getFromProviders(LanguageFindUsages.java:101)
    at com.intellij.lang.findUsages.LanguageFindUsages.getDescriptiveName(LanguageFindUsages.java:64)
    at com.intellij.lang.findUsages.DescriptiveNameUtil.getDescriptiveName(DescriptiveNameUtil.java:35)
    at com.intellij.model.presentation.impl.SymbolPresentationServiceImpl.getSymbolPresentation(SymbolPresentationServiceImpl.kt:38)
    at com.intellij.model.presentation.SymbolPresentationService.getLongDescription(SymbolPresentationService.java:25)
    at com.intellij.model.documentation.impl.DocumentationKt.getSymbolDocumentation(documentation.kt:14)
    at com.intellij.codeInsight.navigation.impl.DocKt.docInfo(doc.kt:13)
    at com.intellij.codeInsight.navigation.impl.SingleSymbolCtrlMouseInfo.getDocInfo(SingleSymbolCtrlMouseInfo.kt:33)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.doExecute(CtrlMouseHandler.java:394)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.lambda$execute$0(CtrlMouseHandler.java:370)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by ahus1** [comment]
java.lang.LinkageError: loader constraint violation: loader 'app' wants to load abstract class com.intellij.openapi.diagnostic.Logger. A different abstract class with the same name was previously loaded by com.intellij.util.lang.PathClassLoader @f5f2bb7. (com.intellij.openapi.diagnostic.Logger is in unnamed module of loader com.intellij.util.lang.PathClassLoader @f5f2bb7)
    at com.intellij.util.lang.ZipResourceFile$MyJarUrlConnection.getJarFile(ZipResourceFile.java:292)
    at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:331)
    at org.jruby.util.URLResource.openInputStream(URLResource.java:151)
    at org.jruby.util.FileResource.inputStream(FileResource.java:93)
    at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:229)
    at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
    at org.jruby.runtime.load.LoadService.load(LoadService.java:343)
    at org.jruby.javasupport.Java.load(Java.java:124)
    at org.jruby.Ruby.initJavaSupport(Ruby.java:1734)
    at org.jruby.Ruby.initBootLibraries(Ruby.java:545)
    at org.jruby.Ruby.<init>(Ruby.java:514)
    at org.jruby.Ruby.newInstance(Ruby.java:706)
    at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:79)
    at org.asciidoctor.jruby.internal.JRubyAsciidoctor.createRubyRuntime(JRubyAsciidoctor.java:130)
    at org.asciidoctor.jruby.internal.JRubyAsciidoctor.createJRubyAsciidoctorInstance(JRubyAsciidoctor.java:117)
    at org.asciidoctor.jruby.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:78)
    at org.asciidoctor.jruby.AsciidoctorJRuby$Factory.create(AsciidoctorJRuby.java:72)
    at org.asciidoc.intellij.AsciiDoc.createInstance(AsciiDoc.java:511)
    at org.asciidoc.intellij.AsciiDoc.initWithExtensions(AsciiDoc.java:321)
    at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:755)
    at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:727)
    at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:716)
    at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.lambda$render$0(AsciiDocPreviewEditor.java:161)
    at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor.lambda$execute$0(LazyApplicationPoolExecutor.java:66)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:829)

**Comment by ahus1** [comment]
Possible cause / contribution to the problem: The AsciiDoc plugin loads some additional JAR files (usually for PDF or diagram creation) then creates a new classloader that delegates to the old one:

https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/src/main/java/org/asciidoc/intellij/AsciiDoc.java#L510-L524

**Comment by ahus1** [comment]
duplicate to #791
