### ISSUE TITLE
IncorrectOperationException when moving a file

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#981]
## Observed vs. expected behavior

When moving file with Ctrl+X/Ctrl+V, an IncorrectOperationException exception occurs. The file is then moved, but the exception is annoying.

## Steps to reproduce

To reproduce the issue:

1. Create a new Antora project (or use [this ](https://github.com/Grolribasi/testrepo)repo)
2. Create a new subdirectory under pages (i.e. "test").
3. Ctrl+X, Ctrl+V the favorites.adoc file from pages to the test subdirectory.
4. Get IDE error. ItelliJ prompts to send a report, I've already submitted a lot of those, not sure if it was of any use.

## Environment

IntelliJ 2021.3.2, plugin 0.36.18

This was originally reported by @Grolribasi on the [Zulip chat](https://antora.zulipchat.com/#narrow/stream/282400-users/topic/IntelliJ.20plugin.2E.20Moving.20files.20causes.20IDE.20exceptions/near/271409046).

Exception: 

<details>

```
com.intellij.util.IncorrectOperationException: Rebind cannot be performed for class org.asciidoc.intellij.psi.AsciiDocFileReference
	at com.intellij.psi.PsiReferenceBase.bindToElement(PsiReferenceBase.java:111)
	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesProcessor.retargetUsages(MoveFilesOrDirectoriesProcessor.java:371)
	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesProcessor.performRefactoringInBranch(MoveFilesOrDirectoriesProcessor.java:246)
	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesProcessor.performRefactoring(MoveFilesOrDirectoriesProcessor.java:142)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRefactoring$10(BaseRefactoringProcessor.java:526)
	at com.intellij.refactoring.BaseRefactoringProcessor.callPerformRefactoring(BaseRefactoringProcessor.java:579)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRefactoring$11(BaseRefactoringProcessor.java:525)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$11(ApplicationImpl.java:911)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.PotemkinProgress.runInSwingThread(PotemkinProgress.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$12(ApplicationImpl.java:911)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:935)
	at com.intellij.openapi.application.impl.ApplicationImpl.runEdtProgressWriteAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithNonCancellableProgressInDispatchThread(ApplicationImpl.java:890)
	at com.intellij.refactoring.BaseRefactoringProcessor.doRefactoring(BaseRefactoringProcessor.java:524)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$execute$2(BaseRefactoringProcessor.java:338)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.refactoring.BaseRefactoringProcessor.execute(BaseRefactoringProcessor.java:336)
	at com.intellij.refactoring.BaseRefactoringProcessor.doRun(BaseRefactoringProcessor.java:259)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:147)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$run$19(BaseRefactoringProcessor.java:640)
	at com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessProvider.disableChecksDuring(NonProjectFileWritingAccessProvider.java:178)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$run$20(BaseRefactoringProcessor.java:642)
	at com.intellij.refactoring.BaseRefactoringProcessor.run(BaseRefactoringProcessor.java:654)
	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesUtil.lambda$doMove$0(MoveFilesOrDirectoriesUtil.java:160)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesUtil.doMove(MoveFilesOrDirectoriesUtil.java:132)
	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesUtil$1.performMove(MoveFilesOrDirectoriesUtil.java:120)
	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesDialog.lambda$doAction$1(MoveFilesOrDirectoriesDialog.java:180)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesDialog.doAction(MoveFilesOrDirectoriesDialog.java:161)
	at com.intellij.refactoring.ui.RefactoringDialog.doRefactorAction(RefactoringDialog.java:129)
	at com.intellij.refactoring.ui.RefactoringDialog$RefactorAction.actionPerformed(RefactoringDialog.java:212)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:701)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1671)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1629)
	at com.intellij.refactoring.ui.RefactoringDialog.show(RefactoringDialog.java:96)
	at com.intellij.refactoring.move.moveFilesOrDirectories.MoveFilesOrDirectoriesUtil.doMove(MoveFilesOrDirectoriesUtil.java:122)
	at com.intellij.refactoring.move.moveFilesOrDirectories.JavaMoveFilesOrDirectoriesHandler.doMove(JavaMoveFilesOrDirectoriesHandler.java:69)
	at com.intellij.refactoring.move.MoveHandler.lambda$doMove$0(MoveHandler.java:130)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:147)
	at com.intellij.refactoring.move.MoveHandler.doMove(MoveHandler.java:126)
	at com.intellij.ide.CopyPasteDelegator$MyEditable.pasteAfterCut(CopyPasteDelegator.java:219)
	at com.intellij.ide.CopyPasteDelegator$MyEditable.lambda$performDefaultPaste$0(CopyPasteDelegator.java:142)
	at com.intellij.openapi.project.DumbService.computeWithAlternativeResolveEnabled(DumbService.java:368)
	at com.intellij.ide.CopyPasteDelegator$MyEditable.performDefaultPaste(CopyPasteDelegator.java:134)
	at com.intellij.ide.CopyPasteDelegator$MyEditable.performPaste(CopyPasteDelegator.java:119)
	at com.intellij.ide.actions.PasteAction.actionPerformed(PasteAction.java:35)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:573)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:265)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:702)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:456)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:224)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

</details>

**Comment by Grolribasi** [comment]
BTW, the file is moved, but if it was referenced somewhere, the xrefs will be broken.

**Comment by ahus1** [comment]
There's now a pre-release 0.37.3 that prevents the exception you've seen. For Antora pages, it also updates references when users move Antora pages. Other families like images, partials etc. would supported in a future (pre-)release. I also need to figure out how to write an automated test.

I would be happy if you could give it a try. I tested the example you provided above; when moving a page with keystrokes or via mouse, the references of a page will change in the component descriptor, in the navigation and other pages. It should work when moving things around within a component and between components.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Grolribasi** [comment]
Sorry for the long wait. Just tested the update, works flawlessly. Thank you!

**Comment by Grolribasi** [comment]
Tested multiple times, no exceptions, no broken xrefs.

But I've noticed one thing: after the files are moved, they get opened in the editor.

**Comment by ahus1** [comment]
Thanks for providing the feedback. I will update this issue when more features are available (which <strike>might</strike> will take some time). 

One hint about opening the files: The dialog has a small checkbox in the lower left corner. Uncheck it, and the moved file will not open in the editor any more.

![image](https://user-images.githubusercontent.com/3957921/154134420-b01b4c08-e98a-4e96-be9f-5454a5e87313.png)

**Comment by Grolribasi** [comment]
Thanks for the tip! Haven't noticed the checkbox.

**Comment by ahus1** [comment]
Upstream issue: https://youtrack.jetbrains.com/issue/IDEA-289206

**Comment by Grolribasi** [comment]
One more issue with exceptions.
Not sure if it's also related to AsciiDoc plugin.
I've already submitted a lot of reports to JetBrains and opened an [issue](https://youtrack.jetbrains.com/issue/IDEA-287942). I forgot about the exceptions for some time since I disabled the plugin. I thought I disabled it only for code inspection, but it appeared that I disabled it for the whole project.
I am attaching the stacktrace FYI.

[stacktrace.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/8107564/stacktrace.txt)

**Comment by Grolribasi** [comment]
Sorry for spamming in this issue, but I have updated my description on JetBrains YouTrack [here](https://youtrack.jetbrains.com/issue/IDEA-287942) with steps to reproduce. We can discuss the issue there if it's related to the plugin or I can open a new issue here.

**Comment by ahus1** [comment]
Hi @Grolribasi - thanks for reporting this. I moved this to a new issue as it seems to be unrelated to this issue.

**Comment by Grolribasi** [comment]
Hello, @ahus1 ! Continuing the issue. Caught an exception in AciiDoc plugin when moving a folder into a folder. Got broken xrefs. Attaching the stacktrace.
[stacktrace-1.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/8160108/stacktrace-1.txt)

**Comment by ahus1** [comment]
Thanks for reporting this. I fix this for the next pre-release and will update this issue once the pre-release is available.

**Comment by ahus1** [comment]
I've been looking at the example of moving a file where the includes inside of the file should be updated. I can reproduce it locally, and I still need to find out about the APIs where I can hook into this. A workaround for this could be to prefix the include page name to be 

```
include::page$test.adoc[tags=text]
```

This way they are valid even when moved to a subfolder. I'll have a look what I can do so this would not be necessary.

**Comment by Grolribasi** [comment]
This was a one-time occasion that I've noticed, so it's not critical at least for me. Probably for others too since nobody reported it yet.

**Comment by ahus1** [comment]
Pre-release 0.37.18 is now available. It supports moving Antora pages and adjusting the relative includes that are part of that page. Please give it a try when you have the time and let me know if it works for you as expected.

I still haven't figured out how to write an automated test for this, and I still want to look into other families like partials what can be done for them. Therefore I'll leave this issue open.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Grolribasi** [comment]
Thanks for notifying about an update. I don't think that there will be any problems, but I will only be able to test it two weeks from now.

**Comment by ahus1** [comment]
Thanks for letting me. I'll close the issue for now. If you experience any problem later, please comment and I'll re-open the issue. Stay safe!

**Comment by ahus1** [comment]
(I appreciate your consistency of noticing things and raising issues - thank you very much!)

**Comment by Grolribasi** [comment]
Just trying to do my part!

**Comment by LukeCz** [comment]
Hi! Thanks for working on the refactoring for moving files, this is an awesome feature and works great for xrefs. However for include:: it is still (0.37.19) creating incorrect Antora syntax, losing the page$.

Example:
include::docs:page$AAA/file.adoc[]
when moved it produces
include::docs:BBB/file.adoc[] instead of include::docs:page$BBB/file.adoc[]

**Comment by mojavelinux** [comment]
Technically this is not wrong as page is the default family for includes.

**Comment by LukeCz** [comment]
It might be but without page$ it does not work in the plugin - highlights in red and "Unresolved Antora reference" on preview.

**Comment by mojavelinux** [comment]
That's not correct then. The family is not required (though a case could be made that it is recommended for clarity).

**Comment by ahus1** [comment]
@LukeCz - I moved this to a new issue. The original issue reported an exception, now you're reporting problem with the implementation for an already closed issue. 

Please add further comments and examples to this new issue #1062.
